# 2. Hyperparameter tuning
Sweeps on the tuning DAGs (101–105), their results, and the candidate check that picks the config
for the main experiments in `3_main_experiments.ipynb`. Shared settings come from `1_mle.ipynb` (its `config` cell); this
notebook's own tuning and selection settings are tagged `config` too, so `3_main_experiments.ipynb` can load them.

In [42]:
%load_ext autoreload
%autoreload 2

import os
import logging

import numpy as np
import pandas as pd
import torch.nn as nn

from ndbn.experiments import run_sweep, run_configs, get_configs, save_chosen_configs
import ndbn.plotting as plotting
from ndbn.notebook_config import load_notebook_config

logging.getLogger("pgmpy").setLevel(logging.ERROR)

# shared settings (RESULTS_DIR, CARD, SAMPLE_SIZES, speed settings, ...) from 1_mle.ipynb
globals().update(load_notebook_config("1_mle.ipynb"))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [43]:
from IPython.display import HTML, display
display(HTML("""<style>
.cell-output-ipywidget-background { background-color: transparent !important; }
:root {
  --jp-widgets-color: var(--vscode-editor-foreground);
  --jp-widgets-font-size: var(--vscode-editor-font-size);
}
</style>"""))

In [44]:

# speed settings (used by the main experiment and all sweeps)
N_JOBS          = -1     # worker processes; -1 = all cores, 1 = serial (old behaviour)
DEVICE_OVERRIDE = "cpu"  # None = auto (cuda if available); tiny per-node nets run best on CPU
TORCH_THREADS   = 1      # torch threads per worker

# All tuning runs on separate DAGs 101..100+SWEEP_DAGS from the same generator
# The main experiment's DAGs (1..SIM) are kept for final evaluation only
TUNE_DAG_OFFSET = 100
assert TUNE_DAG_OFFSET >= SIM, "tuning DAGs overlap the evaluation DAGs"

TUNING_DIR = "results5-parallel"

TIMING_CSV   = os.path.join(TUNING_DIR, "results_timing.csv")
TRIALS_CSV   = os.path.join(TUNING_DIR, "hparam_trials.csv")     # tuning data: sweep trials + chosen configs

## Sweeps
Fixed graph size, varying only the estimator. Writes its own `sweep_tune.csv`, so it
cannot contaminate the main grid's `results.csv`. All tuning runs on separate DAGs
(101–105, `TUNE_DAG_OFFSET`); the main experiment's DAGs 1–5 are kept for final evaluation.

In [45]:
%pip install wandb   
# Offline alternative (sync later with `wandb sync`):  os.environ["WANDB_MODE"] = "offline"

Requirement already satisfied: wandb in .\.venv\Lib\site-packages (0.30.0)
Requirement already satisfied: click>=8.2.0 in .\.venv\Lib\site-packages (from wandb) (8.5.0)
Requirement already satisfied: opentelemetry-api>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-sdk>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from wandb) (26.3)
Requirement already satisfied: platformdirs in .\.venv\Lib\site-packages (from wandb) (4.11.8)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>=5 in .\.venv\Lib\site-packages (from wandb) (7.36.2)
Requirement already satisfied: pydantic<3,>=2.6 in .\.venv\Lib\site-packages (from wandb) (2.13.5)
Requirement already satisfied: pyyaml in .\.venv\Lib\site-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in .\.venv\Lib\site-packages (from wandb) (2.34.2)
Requirement already satisfied: typing-extensions<5,>=4.8 in .\.venv\Lib\site-packages (from wandb) (4.16.0)
Requirement already satisfied: xxhash>=3.0.0 in .\.venv\Lib\site-packages (from wandb) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2026.7.22)
Requirement already satisfied: googleapis-common-protos~=1.52 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-http-transport==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-http-transport[urllib3]==0.66b0->opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-proto==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-sdk>=1.43.0->wandb) (0.66b0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import wandb
wandb.login(relogin=True)

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\Kaylin\_netrc

True

In [ ]:
import os
import torch.nn as nn

WANDB_PROJECT = "neural-cpds-tune"

SWEEP_CSV     = os.path.join(TUNING_DIR, "sweep_tune.csv")
HIST_DIR      = os.path.join(TUNING_DIR, "histories_tune")

SWEEP_N       = 20
SWEEP_ALPHA   = 0.5
SWEEP_DAGS    = 5
SWEEP_K       = [2, 6, 10]          # widen to [2, 4, 6, 8, 10] if time allows
SWEEP_SAMPLES = [600, 1400]

ARMS = [
    {"name": "nn_linear",     "hidden_dims": (),        "activation": None},
    {"name": "nn_32",         "hidden_dims": (32,),     "activation": nn.ReLU},
    {"name": "nn_64_32",      "hidden_dims": (64, 32),  "activation": nn.ReLU},
    {"name": "nn_128_64",     "hidden_dims": (128, 64), "activation": nn.ReLU},
    {"name": "nn_32_nowd",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "weight_decay": 0.0},
    {"name": "nn_32_lr3e3",   "hidden_dims": (32,), "activation": nn.ReLU,
                              "lr": 3e-3},
    {"name": "nn_32_long",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "n_epochs": 1000, "patience": 50},
]

In [ ]:
'''
sweep_df = run_sweep(
    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,
    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,
    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,
    results_dir=TUNING_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)
'''

"\nsweep_df = run_sweep(\n    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,\n    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,\n    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,\n    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,\n    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget\n    n_test=N_TEST,                                         # true KL on cached test.csv\n    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation\n    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,\n)\n"

### No-early-stopping diagnostic
Patience > number of epochs, so nothing stops training. Shows how fast and how far each
architecture overfits at k = 10, N = 600 — compare `train_loss`, `val_loss` and `gap`
per epoch in W&B. Own project, CSV and history folder, so it can't mix with the main sweep.

In [ ]:
'''
NO_ES_EPOCHS = 500
NO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}
              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]

no_es_df = run_sweep(
    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,
    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,
    wandb_project="neural-cpds-no-early-stopping-tune",
    sweep_csv=os.path.join(TUNING_DIR, "sweep_no_es_tune.csv"),
    hist_dir=os.path.join(TUNING_DIR, "histories_no_es_tune"),
    results_dir=TUNING_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)
'''

'\nNO_ES_EPOCHS = 500\nNO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}\n              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]\n\nno_es_df = run_sweep(\n    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,\n    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,\n    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,\n    wandb_project="neural-cpds-no-early-stopping-tune",\n    sweep_csv=os.path.join(RESULTS_DIR, "sweep_no_es_tune.csv"),\n    hist_dir=os.path.join(RESULTS_DIR, "histories_no_es_tune"),\n    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment\'s sample budget\n    n_test=N_TEST,                                         # true KL on cached test.csv\n    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation\n    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,\n)\n'

### Hyperparameter sweep (W&B, Bayesian)
Tuning runs on **separate DAGs** (`dag_idx` > `TUNE_DAG_OFFSET`) drawn from the same generator,
never on the main experiment's DAGs. The chosen setting is then frozen and evaluated on the
main experiment's DAGs, so their test sets never influence any choice.

Each trial is one config scored on every tuning DAG × sample size for the given k. Because
the tuning DAGs are disjoint from evaluation, selecting on `mean_kl` (true KL on the tuning
DAGs' `test.csv`) is legitimate; `mean_val_loss` (validation-only) is the alternative. Both
are logged. AdamW, so `weight_decay` is decoupled and actually regularises. One sweep per
in-degree in `HP_K_VALUES`; `HP_SWEEP_IDS` resumes existing sweeps instead of starting new ones.

In [66]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_TRIALS       = 30
HP_METRIC       = "mean_val_loss"   # validation-only selection; or "mean_kl" (true KL on test.csv)
PARAMS          = {
        "hidden_dims":  {"values": ["32", "64", "32_16", "32_16", "16_16"]}, 
        "lr":           {"values": [6e-5, 1e-4, 3e-4, 6e-4, 1e-3]},     # on the lr snap grid (3-6)
        "dropout":      {"values": [0.0, 0.1, 0.3]},  # on the dropout snap grid (1-3)
        "weight_decay": {"values": [0.0]},              # = FIXED
        "patience":     {"values": [10, 20, 50]},
        "batch_size":   {"values": [32, 64, 128]},
        "optimizer":    {"value": "adamw"},
        "n_epochs":     {"value": 1000},
    }
HP_K_VALUES     = [10, 6, 2]        # one sweep per in-degree, run in this order
HP_CARD         = 4
HP_SAMPLE_SIZES     = [600, 1400] #train+val
HP_SWEEP_NAME   = "smallNN"         # new sweeps are named "<HP_SWEEP_NAME>_c<CARD>_k<in-degree>"
HP_SWEEP_IDS    = {}                # in-degree -> existing sweep id to resume (e.g. {10: "o55ld5z7"});
                                    # in-degrees not listed get a new sweep

In [58]:
from tqdm.auto import tqdm

# one W&B sweep per in-degree in HP_K_VALUES, HP_TRIALS trials each (settings in the cell above)
hp_sweep_ids = {}
for HP_K in HP_K_VALUES:
    HP_CONFIG = {
        "name": f"{HP_SWEEP_NAME}_c{HP_CARD}_k{HP_K}",
        "description": f"new architectures, card {HP_CARD}, in-degree {HP_K}, tuning DAGs "
                       f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                       f"snapped lr / dropout, weight decay fixed at the AdamW default",
        "method": "bayes",
        "metric": {"name": HP_METRIC, "goal": "minimize"},
        "parameters": PARAMS,
    }
    hp_sweep_ids[HP_K] = (HP_SWEEP_IDS.get(HP_K)
                          or wandb.sweep(HP_CONFIG, project=HP_PROJECT))

    run_trial = partial(
        sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
        alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=HP_CARD, val_frac=VAL_FRAC,
        results_dir=TUNING_DIR, n_cached=max(HP_SAMPLE_SIZES), n_test=N_TEST,
        # one file for every sweep: each row records all its settings + sweep_id
        trial_csv=TRIALS_CSV,
        dag_offset=TUNE_DAG_OFFSET,
        n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
    )

    bar = tqdm(total=HP_TRIALS, desc=f"sweep trials k={HP_K}")

    def trial(run_trial=run_trial, bar=bar):    # bind this in-degree's trial and bar
        try:
            run_trial()
        finally:
            bar.update()          # counts even if a trial fails

    wandb.agent(hp_sweep_ids[HP_K], project=HP_PROJECT, count=HP_TRIALS, function=trial)
    bar.close()

print("sweep ids:", hp_sweep_ids)

Create sweep with ID: boc7mevz
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/boc7mevz

sweep trials k=10:   0%|          | 0/30 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dgsdg1it with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sivr15pu with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kp3pmogf with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ri6akcr5 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kxplqgak with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 757pswnv with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hnaemzsg with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cgw7ur0b with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dvvjytv1 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5d516nft with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: b54r2lpu with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: pdq4ln0m with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: v9xijxns with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: f0e8u6pr with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8ad7xyjn with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rzfdgiyw with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: a03vw3um with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: o5rbnb68 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: g2oc3ldl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hp3kpf75 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: w3hd29z7 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7svm88rv with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cotk0k3w with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: zkzw2a6q with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 32z4lb8w with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ubewrdt2 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: exmk28mv with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wfp7k7a5 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cjk7oc65 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ifnecv4v with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

Create sweep with ID: qwcyysc8
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/qwcyysc8

sweep trials k=6:   0%|          | 0/30 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: p8yiosbp with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0biu8xgy with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: j9o8jc8m with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wcz4y48s with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 333savbp with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dcwlw1ic with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: gibffd5h with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: n34e9wej with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8f78zg11 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hvkpdvmg with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bbon0zli with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 43uwd1mo with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bn47isla with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bjje3eei with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 76buji79 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ombmow1o with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: z1y7uqsp with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s9ihfjbb with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: u8k6i0mk with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sr1i9dk1 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1mxx360o with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: aqtndkne with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: gjrnkm99 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0g0kof8q with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: d6dp2gik with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4efucr96 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sg37f2by with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: w34gjf3x with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2ryinxvl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: jp3ucmyp with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

Create sweep with ID: f1obyfeg
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/f1obyfeg

sweep trials k=2:   0%|          | 0/30 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 9j3948ps with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2gf00bxe with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: fuuf6x4c with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ksddz9cf with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qh8tecbf with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: nrkjinsn with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cjvl0nto with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tozu5qoe with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0ojssgsn with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: audunzs2 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: mnshm2jo with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1ulj3zle with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bxwt496z with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: gbdxswxk with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rish2lw0 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: a5decl98 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: m1wo98rp with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: jfkcxxih with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7yb6kr77 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5mpmih1d with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 68sbt18n with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 78hj7wy5 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0p4b9kya with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: exq22w44 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: x2k6u7yl with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: pw2tknkl with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 16_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s03zmbrn with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6ktwz48s with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hq543xld with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dc55jbzl with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

sweep ids: {10: 'boc7mevz', 6: 'qwcyysc8', 2: 'f1obyfeg'}

## Hyperparameter sweep results
From `hparam_trials.csv` (every sweep; each row records all its settings and its `sweep_id`),
filtered with `TRIAL_FILTERS` (any recorded column). Weight decay was found to have a negligible effect
on KL, so it is fixed at the AdamW default of 0.01 (`FIXED`, set in the selection cell above); trials whose
settings are then identical (after rounding, or `SNAP`) are averaged automatically. One table per (in-degree, sample size): the configs
whose **mean validation loss** over the tuning DAGs is not clearly worse than that pair's best (`METRIC = "val_loss"`).
Every config is fitted and validated on the same DAGs and validation rows, so they are compared **paired**:
for each config, `val_gap` is its mean per-DAG excess over the best config's val loss and `val_se` the standard
error of that mean, sd(per-DAG differences) / sqrt(n DAGs). A config is kept if `val_gap <= N_SE * val_se`
(a paired t-test across the DAGs). The raw spread of the val loss across DAGs is not used: it is dominated by
each DAG's own entropy (SE of 0.25-0.75 nats, which would keep nearly every config), and that cancels in the
paired differences. `mean_kl` is shown for reference, bold where within `N_SE` `kl_se` or `REL_TOL` of the best KL. Then one table of the
settings each pair's top configs share, and the configs that are in the top of more than one table, matched on `match_on` (add e.g. `"lr"`, rounded to 1
significant figure).

Every row of `hparam_trials.csv` has a `config_id`: a short hash of its exact settings, so the same
settings always get the same id however often they are run. `n_trials` counts the distinct
configs (`config_id`s) merged into a row, so an exact re-run (e.g. a candidate run) adds to the
averages but not to `n_trials`. `CANDIDATES` / `CHOSEN` below can pick configs by run name or by `config_id`.

In [85]:
# Sweep-result selection (used by the sweep results and candidate cells below)
METRIC        = "val_loss"        # select on mean validation loss (paired over the tuning DAGs); "kl" for true KL
TRIAL_FILTERS = dict(card=CARD)   # any recorded column, e.g. alpha=SWEEP_ALPHA, sweep_id=...
N_SE          = 1                # a config is "top" if its val loss is within N_SE paired SE (over the DAGs) of the best
                                  # (METRIC = "kl": within N_SE kl_se of the best KL)
REL_TOL       = 0.05               # KL: kept (METRIC = "kl") or bold ("val_loss") within N_SE kl_se or REL_TOL of the best KL (e.g. 0.02 = 2%)
MAX_PARAMS    = {10:30000}              # e.g. {10: 100_000}: configs with >= 100000 total params at k=10 are removed from every table (the best is the best under the cap)

# Weight decay was found to have a negligible effect on KL (a 10x change in weight decay moves
# regret by <= ~0.2 percentage points with the other settings fixed), so it is fixed at the AdamW
# default 0.01: trials that then have identical settings are averaged automatically, and every
# chosen config runs with weight decay 0.01.
FIXED         = {"weight_decay": 0.0} # card=2: {"weight_decay": 0.01}
#TODO card2 runs wiuthout fixed "dropout":0.1}
SNAP          = (("lr", (3,6)), ("dropout", (1,3)) )                # e.g. (("lr", (1, 3)),) to snap lr to 1e-4, 3e-4, 1e-3, ...
CARD          = 4

In [86]:
# hparam_trials.csv (all sweeps) plus any older per-k files
trials = plotting.load_trials(TUNING_DIR)

# TRIAL_FILTERS, N_SE, REL_TOL, MAX_PARAMS, FIXED and SNAP come from the selection cell above (weight decay fixed: negligible
# effect; trials that end up identical are averaged). Override here to explore, e.g. N_SE = 2.
# top_values: every config in any table once (settings rounded / snapped / fixed as in the
# tables), for get_configs / run_configs / save_chosen_configs below
tables, top_values = plotting.summarise_trials(trials, n_se=N_SE, rel_tol=REL_TOL, max_params=MAX_PARAMS,
                                               fixed=FIXED, snap=SNAP, metric=METRIC, **TRIAL_FILTERS)

# per table: the values of each setting among its top configs, with counts, ignoring values in
# fewer than min_frac (default 1/5) of them (read down a column to compare tables)
shared  = plotting.shared_settings_table(tables)

# configs in the top of more than one table; drop "lr" from match_on to match across learning rates
common  = plotting.common_configs(tables, match_on=("hidden_dims", "dropout", "lr", "patience", "batch_size"))

configs with 30,000 or more total parameters at in-degree 10 are removed from every table
configs are kept within 1 paired SE of the best val loss (rel_tol is not used for it: a % of entropy + KL means nothing); mean_kl is bold within 1 kl_se or 5% of the best KL
in-degree 2, N = 600: best val loss 17.6704 (paired over 5 DAGs) under the size cap (best over all configs 17.5661)
  2 of 10 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

in-degree 2, N = 1400: best val loss 17.4580 (paired over 5 DAGs) under the size cap (best over all configs 17.3739)
  2 of 10 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

in-degree 6, N = 600: best val loss 24.8693 (paired over 5 DAGs) under the size cap (best over all configs 24.7594)
  2 of 12 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

in-degree 6, N = 1400: best val loss 24.3839 (paired over 5 DAGs) under the size cap (best over all configs 24.1593)
  3 of 12 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

in-degree 10, N = 600: best val loss 24.9376 (paired over 5 DAGs) under the size cap (best over all configs 24.8031)
  4 of 6 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

in-degree 10, N = 1400: best val loss 24.6025 (paired over 5 DAGs) under the size cap (best over all configs 24.4429)
  2 of 6 configs within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000 (weight_decay fixed at 0, lr snapped to 3-6 grid, dropout snapped to 1-3 grid)
  sorted by mean_val_loss (lowest first)

values of each setting among the top configs (within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000) of each table, (count) = number of configs with it, ignoring values in fewer than 20% of them (– = no such value; n_top = 1 means a single config)

,in_degree,sample_size,n_top,hidden_dims,lr,dropout,patience,batch_size
0,2,600,2,"[32] (1), [16, 16] (1)",6e-4,0,50,32
1,2,1400,2,"[32] (1), [16, 16] (1)",6e-4,0,50,32
2,6,600,2,[32],6e-4,0.3,50,"32 (1), 128 (1)"
3,6,1400,3,"[32] (2), [16, 16] (1)",6e-4,0.3,50,"32 (2), 64 (1)"
4,10,600,4,"[32] (2), [16, 16] (2)",6e-4,0.3,50,"32 (1), 64 (1), 128 (2)"
5,10,1400,2,[32],6e-4,0.3,50,"64 (1), 128 (1)"

configs (matched on hidden_dims, dropout, lr, patience, batch_size) in the top (within 1 paired SE (over DAGs) of the best val loss, total params k10 < 30,000) of >= 2 of 6 tables: 6

,hidden_dims,dropout,lr,patience,batch_size,n_tables,top_in,n_trials,config_ids
0,[32],0.3,0.0006,50,64,3,"k6 N1400, k10 N600, k10 N1400",2,"701191f1, fd148b8d"
1,[32],0.3,0.0006,50,128,3,"k6 N600, k10 N600, k10 N1400",2,76f3030a
2,"[16, 16]",0.0,0.0006,50,32,2,"k2 N600, k2 N1400",2,"dd130921, 9dbd5eee"
3,"[16, 16]",0.3,0.0006,50,32,2,"k6 N1400, k10 N600",2,"5762b4c1, a098eeda"
4,[32],0.0,0.0006,50,32,2,"k2 N600, k2 N1400",1,89d0da24
5,[32],0.3,0.0006,50,32,2,"k6 N600, k6 N1400",1,0313ab73

## Candidates
### Run chosen configs on all (in-degree, sample size)
Runs specific configs on the tuning DAGs (101–105) for the in-degrees in `CAND_SWEEPS` (k = 6, 10)
and every sample size in `SWEEP_SAMPLES`, so they are compared like for like (same DAGs, data and seeds). Evaluation DAGs stay untouched. `CANDIDATES` picks rows of the
`top_values` (every config in the sweep-results tables above) by `config_id` (the first column of those tables; `get_configs`) or is a list of config dicts.
A selected config runs with that row's settings (`FIXED` / `SNAP` applied).
They are fitted exactly like sweep
trials and **added to the tuning data** (`TRIALS_CSV`, `source = "candidates"`), so the sweep tables
above include them; in W&B, each config's k=6 run is added to the k=6 sweep and its k=10 run to the k=10
sweep, tagged `candidate`. Configs already
run are skipped on re-running. The comparison table below shows just these configs. Put the chosen config(s) into `CHOSEN` below.

In [87]:
# in-degree -> existing W&B sweep: each config runs on these in-degrees, and its k=6 results go
# into the k=6 sweep, k=10 into the k=10 sweep (tagged "candidate")
CAND_SWEEPS = {2:"f1obyfeg", 6: "qwcyysc8", 10:"boc7mevz"}
#c=2: {2: "qdbol1fm", 6: "yq670x0w", 10: "o55ld5z7"}

# Configs to run: rows of top_values (configs in the sweep-results tables), picked by config_id (the
# first column of those tables), or a list of config dicts written by hand. An id that is in
# no table (e.g. after changing N_SE / MAX_PARAMS) is taken from the tuning data with its exact settings.
# chosen by kl: ["9563d1ea", "4c4f13e7", "ccbfffbc","8d04f306", "3bcb895e", "e569555f", "568bd828", "079cb5e5", "d5698d8f" ]
# small by val loss: ["f50282d2", "b1fc5506", "e45466ed","3ffe7a39", "3e4d22b3", "9709fba4" ]
# c=4: ["5621b5f1", "e27205cc", "4ee70216", "de68e39d", "d0fdba31", "03f47f40" ]
# c=4 small: ["fc0b2513", "3f2f39b4", "8dee1972", "701191f1", "5762b4c1", "89d0da24"]
CANDIDATES = get_configs(top_values, ["fc0b2513", "3f2f39b4", "8dee1972", "701191f1", "5762b4c1", "89d0da24"],
                         trials=trials[trials.card == CARD])   # ids in no table: from the tuning data

# fitted exactly like sweep trials; rows are added to the tuning data (TRIALS_CSV, source="candidates",
# sweep_id of their in-degree's sweep). (config_id, in-degree) pairs already there are skipped on re-running.
cand = run_configs(
    CANDIDATES, k_values=list(CAND_SWEEPS), sweep_ids=CAND_SWEEPS, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=TUNING_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    trial_csv=TRIALS_CSV, dag_offset=TUNE_DAG_OFFSET,
    wandb_project="neural-cpds-hparams",      # same project as the sweeps; None to skip W&B
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

'fc0b2513' is not in the current tables: using its exact settings from the tuning data (20_32x16_lr1e-3)
'3f2f39b4' is not in the current tables: using its exact settings from the tuning data (23_32x16_lr1e-3)
'8dee1972' is not in the current tables: using its exact settings from the tuning data (15_32x16_lr1e-3)

KeyboardInterrupt:

### Candidate comparison
The configs run on every (in-degree, sample size) by the candidate cell above: mean validation loss over the
tuning DAGs (`val k N`), then mean KL (`k N`) for reference. Rows are sorted by average val-loss rank.
**Bold** val loss = not clearly worse than the best config *in this table* for that in-degree and sample size:
its mean per-DAG excess over the best is within `CAND_N_SE` paired standard errors over the DAGs (as in the
sweep tables). **Bold** KL = within `CAND_N_SE` `kl_se` or `CAND_REL_TOL` of the best KL. `max_params` keeps only
configs below a total parameter count (e.g. `{10: 100_000}`: params k10 < 100000); the best is still taken over
all candidates, so the cap never moves the bar (a message says when no candidate under it is within tolerance).

In [88]:
# METRIC (selection cell above): val loss bold = within CAND_N_SE paired SE (over the DAGs) of the best
# candidate; KL bold = within CAND_N_SE SE or CAND_REL_TOL (relative) of the best, whichever is looser;
# with max_params, the best is still over all candidates (also those the filter removes)
# index = config_id: choose the final config(s) below by it
CAND_N_SE   = 2       # statistically indistinguishable from the best
CAND_REL_TOL = 0.05   # KL bold only (not val loss): practically negligible, at most 5% above the best
cand_table = plotting.candidate_table(plotting.load_trials(TUNING_DIR), n_se=CAND_N_SE,
                                      rel_tol=CAND_REL_TOL, metric=METRIC, card=CARD,
                                      max_params=None)   # e.g. {10: 100_000}: total params k10 < 100000
if cand_table.empty:
    print("no candidate runs yet: run the candidate cell above")

chosen configs on every (in-degree, sample size): mean validation loss over the tuning DAGs (val k N), bold = within 2 paired SE (over the DAGs) of the best candidate for that in-degree and sample size; then, for reference, mean KL over the tuning DAGs (k N), bold = within 2 SE or 5% of the best candidate

## Chosen configs
Pick the final NN config(s) for the main experiments by their `config_id` (the first column of the
candidate table above). A `config_id` is fixed (a hash of the exact settings), unlike row numbers in
`top_values`; an id that isn't in `top_values` (e.g. filtered out by `MAX_PARAMS`) raises an error. The first cell is
tagged `config` (settings only), so `3_main_experiments.ipynb` and `4_real_data.ipynb` load `CHOSEN_JSON`
from it; the second saves the configs' settings there and those notebooks read that file. An existing
`chosen_nn.json` with a different choice is kept unless you pass `overwrite=True`, so re-running the
notebook never changes the final model by accident.

In [89]:
# final NN config(s) (tagged "config": 3_main_experiments.ipynb and 4_real_data.ipynb load CHOSEN_JSON)
import os

CHOSEN_JSON = os.path.join(TUNING_DIR, "chosen_nn_c4.json")   # read by 3_main_experiments / 4_real_data
# config_ids of the final config(s), from the candidate table above: pick the candidate run with
# the FIXED / SNAP settings, so the id picked is the id saved (save_chosen_configs notes it if not)
# c=2
# [256,128]: 76cb8405 
# [256]: 7589813f
# [128,64]: 5770cf4b
# [128]: ccbfffbc
# [64,32]: 34bc3fa8
# [64]: dbd55b7b
# [32]: 3e4d22b3
# c=4
# [256]: f0c5e5f0
# [128,64]: ae643bf1
# [64,32]: c6d024ed
# [32,16]: fc0b2513
# [16,16]:
# [32]: 48990a9c

CHOSEN      = ["f0c5e5f0", "ae643bf1", "c6d024ed", "fc0b2513", "48990a9c"]

In [90]:
# keeps an existing chosen_nn.json with different configs; overwrite=True to replace it
# trials (filtered to this card) adds each config's max total params at k=10
save_chosen_configs(get_configs(top_values, CHOSEN, trials=trials[trials.card == CARD]), CHOSEN_JSON,
                    trials=trials[trials.card == CARD], overwrite=True)

'f0c5e5f0' is not in the current tables: using its exact settings from the tuning data (50_256_lr1e-3)
'ae643bf1' is not in the current tables: using its exact settings from the tuning data (12_128x64_lr1e-3)
'c6d024ed' is not in the current tables: using its exact settings from the tuning data (36_64x32_lr1e-3)
'fc0b2513' is not in the current tables: using its exact settings from the tuning data (20_32x16_lr1e-3)
saved 5 config(s) to results5-parallel\chosen_nn_c4.json: ['nn_256', 'nn_128_64', 'nn_64_32', 'nn_32_16', 'nn_32']

[{'name': 'nn_256',
  'config_id': 'f0c5e5f0',
  'max_params_k10': 174416,
  'lr': 0.0006,
  'weight_decay': 0.0,
  'dropout': 0.0,
  'patience': 10,
  'batch_size': 32,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [256],
  'activation': 'ReLU'},
 {'name': 'nn_128_64',
  'config_id': 'ae643bf1',
  'max_params_k10': 247248,
  'lr': 0.0006,
  'weight_decay': 0.0,
  'dropout': 0.3,
  'patience': 50,
  'batch_size': 32,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [128, 64],
  'activation': 'ReLU'},
 {'name': 'nn_64_32',
  'config_id': 'c6d024ed',
  'max_params_k10': 82704,
  'lr': 0.0006,
  'weight_decay': 0.0,
  'dropout': 0.3,
  'patience': 50,
  'batch_size': 32,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [64, 32],
  'activation': 'ReLU'},
 {'name': 'nn_32_16',
  'config_id': 'fc0b2513',
  'max_params_k10': 31152,
  'lr': 0.001,
  'weight_decay': 0.0,
  'dropout': 0.3,
  'patience': 50,
  'batch_size': 32,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [32, 16],
  'activation': 'ReLU'},
 {'name': 'nn_32',
  'config_id': '48990a9c',
  'max_params_k10': 21872,
  'lr': 0.0006,
  'weight_decay': 0.0,
  'dropout': 0.3,
  'patience': 50,
  'batch_size': 64,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [32],
  'activation': 'ReLU'}]