# 2. Hyperparameter tuning
Sweeps on the tuning DAGs (101–105), their results, and the candidate check that picks the config
for the main experiments in `3_main_experiments.ipynb`. Shared settings come from `1_mle.ipynb` (its `config` cell); this
notebook's own tuning and selection settings are tagged `config` too, so `3_main_experiments.ipynb` can load them.

In [8]:
%load_ext autoreload
%autoreload 2

import os
import logging

import numpy as np
import pandas as pd
import torch.nn as nn

from ndbn.experiments import run_sweep, run_configs, get_configs, save_chosen_configs
import ndbn.plotting as plotting
from ndbn.notebook_config import load_notebook_config

logging.getLogger("pgmpy").setLevel(logging.ERROR)

# shared settings (RESULTS_DIR, CARD, SAMPLE_SIZES, speed settings, ...) from 1_mle.ipynb
globals().update(load_notebook_config("1_mle.ipynb"))
print("results folder:", RESULTS_DIR)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
results folder: results5-parallel

In [9]:
from IPython.display import HTML, display
display(HTML("""<style>
.cell-output-ipywidget-background { background-color: transparent !important; }
:root {
  --jp-widgets-color: var(--vscode-editor-foreground);
  --jp-widgets-font-size: var(--vscode-editor-font-size);
}
</style>"""))

## Sweeps
Fixed graph size, varying only the estimator. Writes its own `sweep_tune.csv`, so it
cannot contaminate the main grid's `results.csv`. All tuning runs on separate DAGs
(101–105, `TUNE_DAG_OFFSET`); the main experiment's DAGs 1–5 are kept for final evaluation.

In [60]:
%pip install wandb   
# Offline alternative (sync later with `wandb sync`):  os.environ["WANDB_MODE"] = "offline"

Requirement already satisfied: wandb in .\.venv\Lib\site-packages (0.30.0)
Requirement already satisfied: click>=8.2.0 in .\.venv\Lib\site-packages (from wandb) (8.5.0)
Requirement already satisfied: opentelemetry-api>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-sdk>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from wandb) (26.3)
Requirement already satisfied: platformdirs in .\.venv\Lib\site-packages (from wandb) (4.11.8)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>=5 in .\.venv\Lib\site-packages (from wandb) (7.36.2)
Requirement already satisfied: pydantic<3,>=2.6 in .\.venv\Lib\site-packages (from wandb) (2.13.5)
Requirement already satisfied: pyyaml in .\.venv\Lib\site-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in .\.venv\Lib\site-packages (from wandb) (2.34.2)
Requirement already satisfied: typing-extensions<5,>=4.8 in .\.venv\Lib\site-packages (from wandb) (4.16.0)
Requirement already satisfied: xxhash>=3.0.0 in .\.venv\Lib\site-packages (from wandb) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2026.7.22)
Requirement already satisfied: googleapis-common-protos~=1.52 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-http-transport==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-http-transport[urllib3]==0.66b0->opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-proto==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-sdk>=1.43.0->wandb) (0.66b0)
Note: you may need to restart the kernel to use updated packages.

In [61]:
import wandb
wandb.login(relogin=True)

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\Kaylin\_netrc
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [62]:
import os
import torch.nn as nn

# All tuning (architecture sweep, no-ES diagnostic, hyperparameter sweep) runs on
# separate DAGs 101..100+SWEEP_DAGS from the same generator. The main experiment's
# DAGs (1..SIM) are kept for final evaluation only.
TUNE_DAG_OFFSET = 100
assert TUNE_DAG_OFFSET >= SIM, "tuning DAGs overlap the evaluation DAGs"

WANDB_PROJECT = "neural-cpds-tune"

SWEEP_CSV     = os.path.join(RESULTS_DIR, "sweep_tune.csv")
HIST_DIR      = os.path.join(RESULTS_DIR, "histories_tune")

SWEEP_N       = 20
SWEEP_ALPHA   = 0.5
SWEEP_DAGS    = 5
SWEEP_K       = [2, 6, 10]          # widen to [2, 4, 6, 8, 10] if time allows
SWEEP_SAMPLES = [600, 1400]

ARMS = [
    {"name": "nn_linear",     "hidden_dims": (),        "activation": None},
    {"name": "nn_32",         "hidden_dims": (32,),     "activation": nn.ReLU},
    {"name": "nn_64_32",      "hidden_dims": (64, 32),  "activation": nn.ReLU},
    {"name": "nn_128_64",     "hidden_dims": (128, 64), "activation": nn.ReLU},
    {"name": "nn_32_nowd",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "weight_decay": 0.0},
    {"name": "nn_32_lr3e3",   "hidden_dims": (32,), "activation": nn.ReLU,
                              "lr": 3e-3},
    {"name": "nn_32_long",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "n_epochs": 1000, "patience": 50},
]

In [6]:
'''
sweep_df = run_sweep(
    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,
    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,
    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)
'''

"\nsweep_df = run_sweep(\n    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,\n    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,\n    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,\n    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,\n    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget\n    n_test=N_TEST,                                         # true KL on cached test.csv\n    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation\n    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,\n)\n"

### No-early-stopping diagnostic
Patience > number of epochs, so nothing stops training. Shows how fast and how far each
architecture overfits at k = 10, N = 600 — compare `train_loss`, `val_loss` and `gap`
per epoch in W&B. Own project, CSV and history folder, so it can't mix with the main sweep.

In [7]:
'''
NO_ES_EPOCHS = 500
NO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}
              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]

no_es_df = run_sweep(
    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,
    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,
    wandb_project="neural-cpds-no-early-stopping-tune",
    sweep_csv=os.path.join(RESULTS_DIR, "sweep_no_es_tune.csv"),
    hist_dir=os.path.join(RESULTS_DIR, "histories_no_es_tune"),
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)
'''

'\nNO_ES_EPOCHS = 500\nNO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}\n              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]\n\nno_es_df = run_sweep(\n    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,\n    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,\n    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,\n    wandb_project="neural-cpds-no-early-stopping-tune",\n    sweep_csv=os.path.join(RESULTS_DIR, "sweep_no_es_tune.csv"),\n    hist_dir=os.path.join(RESULTS_DIR, "histories_no_es_tune"),\n    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment\'s sample budget\n    n_test=N_TEST,                                         # true KL on cached test.csv\n    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation\n    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,\n)\n'

### Hyperparameter sweep (W&B, Bayesian)
Tuning runs on **separate DAGs** (`dag_idx` > `TUNE_DAG_OFFSET`) drawn from the same generator,
never on the main experiment's DAGs. The chosen setting is then frozen and evaluated on the
main experiment's DAGs, so their test sets never influence any choice.

Each trial is one config scored on every tuning DAG × sample size for the given k. Because
the tuning DAGs are disjoint from evaluation, selecting on `mean_kl` (true KL on the tuning
DAGs' `test.csv`) is legitimate; `mean_val_loss` (validation-only) is the alternative. Both
are logged. AdamW, so `weight_decay` is decoupled and actually regularises. Start with
k = 10, then check how the frozen setting transfers to k = 2, 6.

In [8]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_TRIALS       = 50
HP_METRIC       = "mean_kl"      # or "mean_val_loss" (validation-only selection)
PARAMS          = {
        "hidden_dims":  {"values": ["32", "32_32", "64", "128", "256",
                                    "32_16_8", "32_16"]}, 
        "lr":           {"values": [6e-5, 1e-4, 3e-4, 6e-4, 1e-3]},     # on the lr snap grid (3-6)
        "dropout":      {"values": [0.0, 0.1, 0.3]},  # on the dropout snap grid (1-3)
        "weight_decay": {"values": [0.0, 0.01]},              # = FIXED
        "patience":     {"values": [10, 20, 50]},
        "batch_size":   {"values": [32, 64, 128]},
        "optimizer":    {"value": "adamw"},
        "n_epochs":     {"value": 1000},
    }

In [9]:
HP_K = 10

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}
hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)   # or reuse an existing id to resume


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: o55ld5z7
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/o55ld5z7

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: xgl8fyj3 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tpp0bgeb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: k1knv7qx with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4o9on9zv with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hjltr40q with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: yy95omv1 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3pcq6tmb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8rtbbwfv with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8b7mni3j with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: yt6dufp4 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: mlomk7zt with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qgwv5384 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sym8gy1q with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ffm2jot1 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: u0ps19s2 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ye4cuywh with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qct298v4 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 83796itt with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 96nd38dl with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 286f5kkt with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: e6y4iqa0 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hwdblif3 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rpnru1i5 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5kdk1s6v with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: xgmc5vp6 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: es3ytbsl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: oc3vvifq with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s3w2pkyu with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 92i0b3rk with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: y5t5fg4q with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wuji4lvl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: boj61crm with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 389ufmsw with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kshs68rq with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: std4kctx with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: l6py9slh with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8wvt5bny with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: vsjyb9as with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: z80vs4f9 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: f9z5lpzs with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: fdho0w8b with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: aa7i1wb3 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 08yknazq with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: zbzq9gmt with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: svpr7klz with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6q6jiicm with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: r4vzeqjo with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: a7rl7jn4 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: fhjrvtl0 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qx9cl2ns with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

In [10]:
HP_K = 6

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}
hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)   # or reuse an existing id to resume


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: yq670x0w
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/yq670x0w

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tf98r9qb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: t4oephz5 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: abt3omyi with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rnr6rehm with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bksnvje5 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: b9t4d7nt with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: o1babwl4 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: aulpai2d with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: y89qa2xp with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sk2q89hs with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: trkt895g with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kqod6ucp with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: yfzx8p5q with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7dkbzhsv with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: vknq8rjw with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3thhth0h with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: zwwuqbl7 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ehqotmyp with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7s1p02c9 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bzjgpt78 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: os4eucxn with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bntmkggp with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: i1ok3pot with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rm4h2l0y with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: m1k4smdo with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 109fx3jk with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: b5ztene4 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wayjjazn with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: abaxgego with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: m6lvhw4p with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: c7xh231z with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: uvll60um with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6nbfib4o with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: enjwa4um with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0z1uflf8 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dybl4gj3 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2usw9abe with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4538h8i7 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tiauwpma with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: yi3cne7k with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: bu6atiwp with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3upqhkqs with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: r18r4y8b with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: nlc11gxq with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ughn6j9d with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: eks30j3t with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kzedoz30 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: quxd0p5v with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: c9f77odb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cp9mrh7v with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

In [11]:
HP_K = 2

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}

hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: qdbol1fm
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/qdbol1fm

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 9hydy1bm with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wo4yookf with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ad236ip4 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rqi3pfde with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: zk4ce94s with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 9a96k1it with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ivpbfqb4 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1bgtcz41 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: n153amw6 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: x1f0aj81 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 65zkrutu with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: nf6unn3s with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: yo0mocjy with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8msaqz9m with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 83oqtpot with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: o7fzyoc6 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hvfxxv2m with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ho7wl5wp with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s1od5q5q with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: djfbtzov with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: lnz6o6ac with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: i9r4q66i with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qzple2qn with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 93u0vuqf with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0ya00rou with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wthidkid with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1wvzdj4u with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: lr9z0kez with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: sbdcl0k0 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0t9wl0bn with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: eea5sffc with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tc3bobc3 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8ld0gj3f with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: t0dl0fvl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0e7kw7wz with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: woqea46c with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ftzhnlai with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s4521dz3 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hbdkq244 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: pw0mt1d4 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: q3f7nvi0 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_16_8
wandb: 	lr: 6e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: dys69gky with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2qyv75ew with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wapjbesi with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5pd9xl3s with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1otnxmgr with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: jcjy5ut7 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: zrtk5rd5 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: emkupidl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: s06shrj3 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

## Hyperparameter sweep results
From `hparam_trials.csv` (every sweep; each row records all its settings and its `sweep_id`),
filtered with `TRIAL_FILTERS` (any recorded column). Weight decay was found to have a negligible effect
on KL, so it is fixed at the AdamW default of 0.01 (`FIXED`, set in the selection cell above); trials whose
settings are then identical (after rounding, or `SNAP`) are averaged automatically. One table per (in-degree, sample size): the configs
whose mean KL over the tuning DAGs is within one `kl_se` of that pair's best. Then one table of the
settings each pair's top configs share, and the configs that are in the top of more than one table, matched on `match_on` (add e.g. `"lr"`, rounded to 1
significant figure).

Every row of `hparam_trials.csv` has a `config_id`: a short hash of its exact settings, so the same
settings always get the same id however often they are run. `n_trials` counts the distinct
configs (`config_id`s) merged into a row, so an exact re-run (e.g. a candidate run) adds to the
averages but not to `n_trials`. `CANDIDATES` / `CHOSEN` below can pick configs by run name or by `config_id`.

In [57]:
# Sweep-result selection (used by the sweep results and candidate cells below)
TRIAL_FILTERS = dict(card=CARD)   # any recorded column, e.g. alpha=SWEEP_ALPHA, sweep_id=...
N_SE          = 2                 # a config is "top" if its mean KL is within N_SE kl_se of the best
REL_TOL       = 0.05               # ... or within REL_TOL of the best KL (e.g. 0.02 = 2%: practically negligible)
MAX_PARAMS    = {10:80000}              # e.g. {10: 100_000}: configs with >= 100000 total params at k=10 are removed from every table (the best is still over all configs)

# Weight decay was found to have a negligible effect on KL (a 10x change in weight decay moves
# regret by <= ~0.2 percentage points with the other settings fixed), so it is fixed at the AdamW
# default 0.01: trials that then have identical settings are averaged automatically, and every
# chosen config runs with weight decay 0.01.
FIXED         = {"weight_decay": 0.01, "dropout":0.1}
SNAP          = (("lr", (3,6)), ("dropout", (1,3)) )                # e.g. (("lr", (1, 3)),) to snap lr to 1e-4, 3e-4, 1e-3, ...

In [90]:
# hparam_trials.csv (all sweeps) plus any older per-k files
trials = plotting.load_trials(RESULTS_DIR)

# TRIAL_FILTERS, N_SE, REL_TOL, MAX_PARAMS, FIXED and SNAP come from the selection cell above (weight decay fixed: negligible
# effect; trials that end up identical are averaged). Override here to explore, e.g. N_SE = 2.
# top_values: every config in any table once (settings rounded / snapped / fixed as in the
# tables), for get_configs / run_configs / save_chosen_configs below
tables, top_values = plotting.summarise_trials(trials, n_se=N_SE, rel_tol=REL_TOL, max_params=MAX_PARAMS,
                                               fixed=FIXED, snap=SNAP, **TRIAL_FILTERS)

# per table: the values of each setting among its top configs, with counts, ignoring values in
# fewer than min_frac (default 1/5) of them (read down a column to compare tables)
shared  = plotting.shared_settings_table(tables)

# configs in the top of more than one table; match_on=(..., "lr") also matches lr (rounded)
common  = plotting.common_configs(tables, match_on=("hidden_dims", "dropout", "patience", "batch_size"))

configs with 80,000 or more total parameters at in-degree 10 are removed from every table
in-degree 2, N = 600: best KL 0.1067 ± 0.0011 (over all configs, also those over the size cap) -> 3 of 44 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

in-degree 2, N = 1400: best KL 0.0404 ± 0.0006 (over all configs, also those over the size cap) -> 5 of 44 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

in-degree 6, N = 600: best KL 0.7806 ± 0.0056 (over all configs, also those over the size cap) -> 7 of 27 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

in-degree 6, N = 1400: best KL 0.3680 ± 0.0035 (over all configs, also those over the size cap) -> 2 of 27 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

in-degree 10, N = 600: best KL 2.2284 ± 0.0085 (over all configs, also those over the size cap) -> 17 of 48 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

in-degree 10, N = 1400: best KL 1.4160 ± 0.0076 (over all configs, also those over the size cap) -> 8 of 48 configs (weight_decay fixed at 0.01) (dropout fixed at 0.1) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se or 5%, total params k10 < 80,000

values of each setting among the top configs (within 2 kl_se or 5%, total params k10 < 80,000) of each table, (count) = number of configs with it, ignoring values in fewer than 20% of them (– = no such value; n_top = 1 means a single config)

,in_degree,sample_size,n_top,hidden_dims,lr,patience,batch_size
0,2,600,3,"[64, 32] (2), [128] (1)",6e-4,"20 (2), 50 (1)","32 (1), 64 (1), 128 (1)"
1,2,1400,5,"[64, 32] (2), [128] (1), [64] (1), [32] (1)",6e-4,"20 (1), 50 (4)","32 (4), 128 (1)"
2,6,600,7,"[128] (5), [64, 32] (2)",6e-4 (6),"20 (2), 50 (5)","32 (2), 64 (2), 128 (3)"
3,6,1400,2,"[128] (1), [64, 32] (1)",6e-4,50,128
4,10,600,17,"[128] (8), [64, 32] (5)",6e-4 (13),50 (14),"32 (8), 64 (5), 128 (4)"
5,10,1400,8,"[64, 32] (4), [64, 32, 16] (4)","3e-4 (3), 6e-4 (5)",50,"32 (3), 64 (3), 128 (2)"

configs (matched on hidden_dims, dropout, patience, batch_size) in the top (within 2 kl_se or 5%, total params k10 < 80,000) of >= 2 of 6 tables: 11

,hidden_dims,dropout,patience,batch_size,n_tables,top_in,n_trials
0,"[64, 32]",0.1,50,128,6,"k2 N600, k2 N1400, k6 N600, k6 N1400, k10 N600...",4
1,"[64, 32]",0.1,20,32,4,"k2 N600, k2 N1400, k6 N600, k10 N600",3
2,[128],0.1,50,32,3,"k2 N1400, k6 N600, k10 N600",5
3,[128],0.1,50,128,3,"k6 N600, k6 N1400, k10 N600",4
4,[128],0.1,20,64,3,"k2 N600, k6 N600, k10 N600",3
5,[128],0.1,50,64,2,"k6 N600, k10 N600",3
6,"[64, 32, 16]",0.1,50,32,2,"k10 N600, k10 N1400",2
7,"[64, 32]",0.1,50,32,2,"k10 N600, k10 N1400",2
8,"[64, 32]",0.1,50,64,2,"k10 N600, k10 N1400",2
9,[64],0.1,50,32,2,"k2 N1400, k10 N600",2
10,"[64, 32, 16]",0.1,50,64,2,"k10 N600, k10 N1400",1

## Candidates
### Run chosen configs on all (in-degree, sample size)
Runs specific configs on the tuning DAGs (101–105) for the in-degrees in `CAND_SWEEPS` (k = 6, 10)
and every sample size in `SWEEP_SAMPLES`, so they are compared like for like (same DAGs, data and seeds). Evaluation DAGs stay untouched. `CANDIDATES` picks rows of the
`top_values` (every config in the sweep-results tables above) by `config_id` (the first column of those tables; `get_configs`) or is a list of config dicts.
A selected config runs with that row's settings (`FIXED` / `SNAP` applied).
They are fitted exactly like sweep
trials and **added to the tuning data** (`TRIALS_CSV`, `source = "candidates"`), so the sweep tables
above include them; in W&B, each config's k=6 run is added to the k=6 sweep and its k=10 run to the k=10
sweep, tagged `candidate`. Configs already
run are skipped on re-running. The comparison table below shows just these configs. Put the chosen config(s) into `CHOSEN` below.

In [ ]:
# in-degree -> existing W&B sweep: each config runs on these in-degrees, and its k=6 results go
# into the k=6 sweep, k=10 into the k=10 sweep (tagged "candidate")
CAND_SWEEPS = {2: "qdbol1fm", 6: "yq670x0w", 10: "o55ld5z7"}

# Configs to run: rows of top_values (configs in the sweep-results tables), picked by config_id (the
# first column of those tables), or a list of config dicts written by hand.
#chosen by kl: ["9563d1ea", "4c4f13e7", "ccbfffbc","8d04f306", "3bcb895e", "e569555f", "568bd828", "079cb5e5", "d5698d8f" ]
CANDIDATES = get_configs(top_values, ["9563d1ea", "4c4f13e7", "ccbfffbc","8d04f306", "3bcb895e", "e569555f", "568bd828", "079cb5e5", "d5698d8f" ])

# fitted exactly like sweep trials; rows are added to the tuning data (TRIALS_CSV, source="candidates",
# sweep_id of their in-degree's sweep). (config_id, in-degree) pairs already there are skipped on re-running.
cand = run_configs(
    CANDIDATES, k_values=list(CAND_SWEEPS), sweep_ids=CAND_SWEEPS, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    trial_csv=TRIALS_CSV, dag_offset=TUNE_DAG_OFFSET,
    wandb_project="neural-cpds-hparams",      # same project as the sweeps; None to skip W&B
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

'8d04f306' is the same config as 'ccbfffbc' after tidying (FIXED / SNAP): selected once
'd5698d8f' is the same config as '568bd828' after tidying (FIXED / SNAP): selected once

configs:   0%|          | 0/7 [00:00<?, ?it/s]

### Candidate comparison
The configs run on every (in-degree, sample size) by the candidate cell above: mean KL over the
tuning DAGs. **Bold** = close to the best config *in this table* for that in-degree and sample size:
within `CAND_N_SE` standard errors of it (statistically indistinguishable) or within `CAND_REL_TOL` of
its KL, e.g. 2% (practically negligible), whichever is looser. `max_params` keeps only configs below a
total parameter count (e.g. `{10: 100_000}`: params k10 < 100000); the best is still taken over all
candidates, so the cap never moves the bar (a message says when no candidate under it is within tolerance).

In [92]:
# bold = within CAND_N_SE SE or CAND_REL_TOL (relative) of the best candidate, whichever is looser;
# with max_params, the best is still over all candidates (also those the filter removes)
# index = config_id: choose the final config(s) below by it
CAND_N_SE   = 2       # statistically indistinguishable from the best
CAND_REL_TOL = 0.05   # practically negligible: KL at most 5% above the best
cand_table = plotting.candidate_table(plotting.load_trials(RESULTS_DIR), n_se=CAND_N_SE,
                                      rel_tol=CAND_REL_TOL,
                                      max_params=None)   # e.g. {10: 100_000}: total params k10 < 100000
if cand_table.empty:
    print("no candidate runs yet: run the candidate cell above")

chosen configs on every (in-degree, sample size): mean KL over the tuning DAGs; bold = within 2 SE or 5% of the best candidate for that in-degree and sample size; then mean validation loss (val k N), bold = within the same window (in nats) of the best val loss

## Chosen configs
Pick the final NN config(s) for the main experiments by their `config_id` (the first column of the
candidate table above). A `config_id` is fixed (a hash of the exact settings), unlike row numbers in
`top_values`; an id that isn't in `top_values` (e.g. filtered out by `MAX_PARAMS`) raises an error. The first cell is
tagged `config` (settings only), so `3_main_experiments.ipynb` and `4_real_data.ipynb` load `CHOSEN_JSON`
from it; the second saves the configs' settings there and those notebooks read that file. An existing
`chosen_nn.json` with a different choice is kept unless you pass `overwrite=True`, so re-running the
notebook never changes the final model by accident.

In [98]:
# final NN config(s) (tagged "config": 3_main_experiments.ipynb and 4_real_data.ipynb load CHOSEN_JSON)
import os

CHOSEN_JSON = os.path.join(RESULTS_DIR, "chosen_nn.json")   # read by 3_main_experiments / 4_real_data
# config_ids of the final config(s), from the candidate table above: pick the candidate run with
# the FIXED / SNAP settings, so the id picked is the id saved (save_chosen_configs notes it if not)
# [256,128]: 76cb8405  (89bf682b is the older dropout-0.0 run; it would run as 76cb8405)
# [256]: 7589813f
# [128,64]: 5770cf4b
# [128]: ccbfffbc
# [64,32]: 34bc3fa8
# [64]: dbd55b7b

CHOSEN      = ["76cb8405", "7589813f", "5770cf4b", "ccbfffbc", "34bc3fa8", "dbd55b7b"]

In [101]:
# keeps an existing chosen_nn.json with different configs; overwrite=True to replace it
# trials (filtered to this card) adds each config's max total params at k=10
save_chosen_configs(get_configs(top_values, CHOSEN), CHOSEN_JSON,
                    trials=trials[trials.card == CARD])

saved 6 config(s) to results5-parallel\chosen_nn.json: ['nn_256_128', 'nn_256', 'nn_128_64', 'nn_128', 'nn_64_32', 'nn_64']

[{'name': 'nn_256_128',
  'config_id': '76cb8405',
  'max_params_k10': 742696,
  'lr': 0.0003,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 20,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [256, 128],
  'activation': 'ReLU'},
 {'name': 'nn_256',
  'config_id': '7589813f',
  'max_params_k10': 89896,
  'lr': 0.0006,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [256],
  'activation': 'ReLU'},
 {'name': 'nn_128_64',
  'config_id': '5770cf4b',
  'max_params_k10': 207528,
  'lr': 0.0003,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [128, 64],
  'activation': 'ReLU'},
 {'name': 'nn_128',
  'config_id': 'ccbfffbc',
  'max_params_k10': 44968,
  'lr': 0.0006,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [128],
  'activation': 'ReLU'},
 {'name': 'nn_64_32',
  'config_id': '34bc3fa8',
  'max_params_k10': 62824,
  'lr': 0.0006,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [64, 32],
  'activation': 'ReLU'},
 {'name': 'nn_64',
  'config_id': 'dbd55b7b',
  'max_params_k10': 22504,
  'lr': 0.0006,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [64],
  'activation': 'ReLU'}]