# 2. Hyperparameter tuning
Sweeps on the tuning DAGs (101–105), their results, and the candidate check that picks the config
for the main experiments in `3_main_experiments.ipynb`. Shared settings come from `1_mle.ipynb` (its `config` cell); this
notebook's own tuning and selection settings are tagged `config` too, so `3_main_experiments.ipynb` can load them.

In [1]:
%load_ext autoreload
%autoreload 2

import os
import logging

import numpy as np
import pandas as pd
import torch.nn as nn

from ndbn.experiments import run_sweep, run_configs, save_chosen_configs
import ndbn.plotting as plotting
from ndbn.notebook_config import load_notebook_config

logging.getLogger("pgmpy").setLevel(logging.ERROR)

# shared settings (RESULTS_DIR, CARD, SAMPLE_SIZES, speed settings, ...) from 1_mle.ipynb
globals().update(load_notebook_config("1_mle.ipynb"))
print("results folder:", RESULTS_DIR)

results folder: results5-parallel

In [2]:
from IPython.display import HTML, display
display(HTML("""<style>
.cell-output-ipywidget-background { background-color: transparent !important; }
:root {
  --jp-widgets-color: var(--vscode-editor-foreground);
  --jp-widgets-font-size: var(--vscode-editor-font-size);
}
</style>"""))

## Sweeps
Fixed graph size, varying only the estimator. Writes its own `sweep_tune.csv`, so it
cannot contaminate the main grid's `results.csv`. All tuning runs on separate DAGs
(101–105, `TUNE_DAG_OFFSET`); the main experiment's DAGs 1–5 are kept for final evaluation.

In [4]:
%pip install wandb   
# Offline alternative (sync later with `wandb sync`):  os.environ["WANDB_MODE"] = "offline"

Requirement already satisfied: wandb in ./.venv/lib/python3.14/site-packages (0.30.0)
Requirement already satisfied: click>=8.2.0 in ./.venv/lib/python3.14/site-packages (from wandb) (8.5.0)
Requirement already satisfied: opentelemetry-api>=1.43.0 in ./.venv/lib/python3.14/site-packages (from wandb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.43.0 in ./.venv/lib/python3.14/site-packages (from wandb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.43.0 in ./.venv/lib/python3.14/site-packages (from wandb) (1.45.1)
Requirement already satisfied: packaging in ./.venv/lib/python3.14/site-packages (from wandb) (26.3)
Requirement already satisfied: platformdirs in ./.venv/lib/python3.14/site-packages (from wandb) (4.11.8)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>=5 in ./.venv/lib/python3.14/site-packages (from wandb) (7.36.2)
Requirement already satisfied: pydantic<3,>=2.6 in ./.venv/lib/python3.14/site-packages (from wandb) (2.14.0)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.14/site-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in ./.venv/lib/python3.14/site-packages (from wandb) (2.34.2)
Requirement already satisfied: typing-extensions<5,>=4.8 in ./.venv/lib/python3.14/site-packages (from wandb) (4.16.0)
Requirement already satisfied: xxhash>=3.0.0 in ./.venv/lib/python3.14/site-packages (from wandb) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=2.6->wandb) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.0 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=2.6->wandb) (2.50.0)
Requirement already satisfied: typing-inspection>=0.4.4 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=2.6->wandb) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.14/site-packages (from requests<3,>=2.0.0->wandb) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.14/site-packages (from requests<3,>=2.0.0->wandb) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.14/site-packages (from requests<3,>=2.0.0->wandb) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.14/site-packages (from requests<3,>=2.0.0->wandb) (2026.7.22)
Requirement already satisfied: googleapis-common-protos~=1.52 in ./.venv/lib/python3.14/site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-http-transport==0.66b1 in ./.venv/lib/python3.14/site-packages (from opentelemetry-exporter-http-transport[requests]==0.66b1->opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b1 in ./.venv/lib/python3.14/site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.1 in ./.venv/lib/python3.14/site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.1)
Requirement already satisfied: opentelemetry-proto==1.45.1 in ./.venv/lib/python3.14/site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b1 in ./.venv/lib/python3.14/site-packages (from opentelemetry-sdk>=1.43.0->wandb) (0.66b1)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import wandb
wandb.login(relogin=True)

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.
wandb: Appending key for api.wandb.ai to your netrc file: /home/kaylin/.netrc

True

In [9]:
import os
import torch.nn as nn

# All tuning (architecture sweep, no-ES diagnostic, hyperparameter sweep) runs on
# separate DAGs 101..100+SWEEP_DAGS from the same generator. The main experiment's
# DAGs (1..SIM) are kept for final evaluation only.
TUNE_DAG_OFFSET = 100
assert TUNE_DAG_OFFSET >= SIM, "tuning DAGs overlap the evaluation DAGs"

WANDB_PROJECT = "neural-cpds-tune"

SWEEP_CSV     = os.path.join(RESULTS_DIR, "sweep_tune.csv")
HIST_DIR      = os.path.join(RESULTS_DIR, "histories_tune")

SWEEP_N       = 20
SWEEP_ALPHA   = 0.5
SWEEP_DAGS    = 5
SWEEP_K       = [2, 6, 10]          # widen to [2, 4, 6, 8, 10] if time allows
SWEEP_SAMPLES = [600, 1400]

ARMS = [
    {"name": "nn_linear",     "hidden_dims": (),        "activation": None},
    {"name": "nn_32",         "hidden_dims": (32,),     "activation": nn.ReLU},
    {"name": "nn_64_32",      "hidden_dims": (64, 32),  "activation": nn.ReLU},
    {"name": "nn_128_64",     "hidden_dims": (128, 64), "activation": nn.ReLU},
    {"name": "nn_32_nowd",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "weight_decay": 0.0},
    {"name": "nn_32_lr3e3",   "hidden_dims": (32,), "activation": nn.ReLU,
                              "lr": 3e-3},
    {"name": "nn_32_long",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "n_epochs": 1000, "patience": 50},
]

In [6]:
sweep_df = run_sweep(
    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,
    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,
    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

sweep runs:   0%|          | 0/210 [00:00<?, ?it/s]

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: setting up run c5kpzxpi
wandb: setting up run 9i9p4g8b
wandb: setting up run zleuptg4
wandb: setting up run pfsasbcj
wandb: setting up run 3yj8c42a
wandb: setting up run d2a8ptpl
wandb: setting up run wrf2viro
wandb: setting up run fqugji4b
wandb: setting up run oj7dxh4m
wandb: setting up run t6inuza5
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: setting up run 000jju9u
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: setting up run jmcd1taa
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-pfsasbcj
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_linear_k2_n600
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/pfsasbcj
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-zleuptg4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_64_32_k2_n1400
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/zleuptg4
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-fqugji4b
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_linear_k2_n1400
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/fqugji4b
wandb: Tracking run with wandb version 0.30.0
wandb: Tracking run with wandb version 0.30.0
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-3yj8c42a
wandb: Run `wandb offline` to turn off syncing.
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-d2a8ptpl
wandb: Run `wandb offline` to turn off syncing.
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-wrf2viro
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_64_32_k2_n600
wandb: Syncing run nn_128_64_k2_n600
wandb: Syncing run nn_32_k2_n1400
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/d2a8ptpl
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/wrf2viro
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/3yj8c42a
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005550-000jju9u
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_32_nowd_k2_n600
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/000jju9u
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-t6inuza5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_32_nowd_k2_n1400
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/t6inuza5
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-c5kpzxpi
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_32_k2_n600
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/c5kpzxpi
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-oj7dxh4m
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_32_long_k2_n600
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/oj7dxh4m
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005549-9i9p4g8b
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_128_64_k2_n1400
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/9i9p4g8b
wandb: Tracking run with wandb version 0.30.0
wandb: Run data is saved locally in /home/kaylin/Neural-Discrete-Bayesian-Network/wandb/run-20261011_005550-jmcd1taa
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run nn_32_lr3e3_k2_n600
wandb: ⭐️ View project at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune
wandb: 🚀 View run at https://wandb.ai/kay-asp-wits-university/neural-cpds-tune/runs/jmcd1taa
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
Exception in thread wandb-ServiceFinalizer:
Traceback (most recent call last):
  File "/usr/lib/python3.14/threading.py", line 1082, in _bootstrap_inner
    self._context.run(self.run)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.14/threading.py", line 1024, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_finalizer.py", line 96, in _publish_queue
    self._asyncer.run(functools.partial(self._client.publish, request))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/asyncio_manager.py", line 145, in run
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.14/concurrent/futures/_base.py", line 450, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.14/concurrent/futures/_base.py", line 395, in __get_result
    raise self._exception
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/asyncio_manager.py", line 238, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 42, in publish
    await self._send_server_request(request)
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 84, in _send_server_request
    await self._drain_writer()
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 92, in _drain_writer
    await self._writer.drain()
  File "/usr/lib/python3.14/asyncio/streams.py", line 386, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.14/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
Exception in thread wandb-ServiceFinalizer:
Traceback (most recent call last):
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/asyncio_manager.py", line 195, in fn_wrap_exceptions
    await fn()
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 42, in publish
    await self._send_server_request(request)
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 75, in _send_server_request
    raise self._broken_exc.with_traceback(self._broken_tb)
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 84, in _send_server_request
    await self._drain_writer()
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 92, in _drain_writer
    await self._writer.drain()
  File "/usr/lib/python3.14/asyncio/streams.py", line 386, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.14/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Finishing previous runs because reinit is set to 'finish_previous'.
Exception in thread wandb-ServiceFinalizerException in thread :
wandb-ServiceFinalizerTraceback (most recent call last):
:
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/asyncio_manager.py", line 195, in fn_wrap_exceptions
    await fn()
  File "/home/kaylin/Neural-Discrete-Bayesian-Network/.venv/lib/python3.14/site-packages/wandb/sdk/lib/service/service_client.py", line 42, in publish
    await self._send_server_request(request)

KeyboardInterrupt:

### No-early-stopping diagnostic
Patience > number of epochs, so nothing stops training. Shows how fast and how far each
architecture overfits at k = 10, N = 600 — compare `train_loss`, `val_loss` and `gap`
per epoch in W&B. Own project, CSV and history folder, so it can't mix with the main sweep.

In [ ]:
NO_ES_EPOCHS = 500
NO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}
              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]

no_es_df = run_sweep(
    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,
    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,
    wandb_project="neural-cpds-no-early-stopping-tune",
    sweep_csv=os.path.join(RESULTS_DIR, "sweep_no_es_tune.csv"),
    hist_dir=os.path.join(RESULTS_DIR, "histories_no_es_tune"),
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

### Hyperparameter sweep (W&B, Bayesian)
Tuning runs on **separate DAGs** (`dag_idx` > `TUNE_DAG_OFFSET`) drawn from the same generator,
never on the main experiment's DAGs. The chosen setting is then frozen and evaluated on the
main experiment's DAGs, so their test sets never influence any choice.

Each trial is one config scored on every tuning DAG × sample size for the given k. Because
the tuning DAGs are disjoint from evaluation, selecting on `mean_kl` (true KL on the tuning
DAGs' `test.csv`) is legitimate; `mean_val_loss` (validation-only) is the alternative. Both
are logged. AdamW, so `weight_decay` is decoupled and actually regularises. Start with
k = 10, then check how the frozen setting transfers to k = 2, 6.

In [ ]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_TRIALS       = 50
HP_METRIC       = "mean_kl"      # or "mean_val_loss" (validation-only selection)
PARAMS          = {
        "hidden_dims":  {"values": ["32", "32_32", "64", "128", "256",
                                    "32_16_8", "32_16"]}, 
        "lr":           {"values": [6e-5, 1e-4, 3e-4, 6e-4, 1e-3]},     # on the lr snap grid (3-6)
        "dropout":      {"values": [0.0, 0.1, 0.3]},  # on the dropout snap grid (1-3)
        "weight_decay": {"values": [0.0, 0.01]},              # = FIXED
        "patience":     {"values": [10, 20, 50]},
        "batch_size":   {"values": [32, 64, 128]},
        "optimizer":    {"value": "adamw"},
        "n_epochs":     {"value": 1000},
    }

In [11]:
HP_K = 10

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}
hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)   # or reuse an existing id to resume


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: 4j5rt06a
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/4j5rt06a

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: z7f0bpi1 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: a97r3ljs with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: p95jamnj with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: cw32jass with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: ragloa0l with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 1uweqvd6 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: crxass1b with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: pha4is10 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: a0888knq with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: ez7xv55g with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: kd4ucefb with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: m5dh3451 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: qjsky6v3 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 15vule93 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: y3sjmeku with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 6fndn66b with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: iu4ohez9 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: gg1rws50 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 1vx5mzrb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 0wmwfpn4 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: j7awy26c with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: nn4exv8c with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: wxmkq1sk with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 8vxqnypd with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: icf7n1b9 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 6djnd571 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: s1yfm316 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: jtrwlofx with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: zt1nv80z with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: v4z9bxkj with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 40vitleb with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: ymb05j3p with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: dfh0q37s with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 719rsj86 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: rlvkzuai with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 058e1ox7 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 9v10cwa9 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: bgdeeyp4 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 64
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: oluw1w42 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: jyuafgqb with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: drbpqgh9 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 1tk1tgwc with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: lzokb9j0 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: rtcvod3t with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 128
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: zg2unql8 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32_16
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: aos8xa5l with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32_32_32
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: yz3lmxr6 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: b7i5ip8p with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)
/home/kaylin/Neural-Discrete-Bayesian-Network/ndbn/models.py:66: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  idx = torch.as_tensor(data[parents].to_numpy(np.int64), device=DEVICE)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: crwmlaqf with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128
wandb: 	lr: 0.0006
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /home/kaylin/.netrc.
wandb: Agent Starting Run: 68yirfl5 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256
wandb: 	lr: 0.001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

In [12]:
HP_K = 6

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}
hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)   # or reuse an existing id to resume


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: y1764wc5
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/y1764wc5

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
HP_K = 2

HP_CONFIG = {
    "name": f"smallNN_c{CARD}_k{HP_K}",
    "description": f"new architectures, card {CARD}, in-degree {HP_K}, tuning DAGs "
                   f"{TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, N = {SWEEP_SAMPLES}, "
                   f"snapped lr / dropout, weight decay fixed at the AdamW default",
    "method": "bayes",                # every combination, once
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": PARAMS,
}

hp_sweep_id = wandb.sweep(HP_CONFIG, project=HP_PROJECT)


run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: rmhp979u
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/rmhp979u

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: fjt1sxyv with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 33vepen5 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64_32128_128
wandb: 	lr: 0.0001
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.01

## Hyperparameter sweep results
From `hparam_trials.csv` (every sweep; each row records all its settings and its `sweep_id`),
filtered with `TRIAL_FILTERS` (any recorded column). Weight decay was found to have a negligible effect
on KL, so it is fixed at the AdamW default of 0.01 (`FIXED`, set in the selection cell above); trials whose
settings are then identical (after rounding, or `SNAP`) are averaged automatically. One table per (in-degree, sample size): the configs
whose mean KL over the tuning DAGs is within one `kl_se` of that pair's best. Then one table of the
settings each pair's top configs share, and the configs that are in the top of more than one table, matched on `match_on` (add e.g. `"lr"`, rounded to 1
significant figure).

In [ ]:
# Sweep-result selection (used by the sweep results and candidate cells below)
TRIAL_FILTERS = dict(card=CARD)   # any recorded column, e.g. alpha=SWEEP_ALPHA, sweep_id=...
N_SE          = 2                 # a config is "top" if its mean KL is within N_SE kl_se of the best

# Weight decay was found to have a negligible effect on KL (a 10x change in weight decay moves
# regret by <= ~0.2 percentage points with the other settings fixed), so it is fixed at the AdamW
# default 0.01: trials that then have identical settings are averaged automatically, and every
# chosen config runs with weight decay 0.01.
FIXED         = {"weight_decay": 0.01}
SNAP          = (("lr", (3,6)), ("dropout", (1,3)) )                # e.g. (("lr", (1, 3)),) to snap lr to 1e-4, 3e-4, 1e-3, ...

In [ ]:
# hparam_trials.csv (all sweeps) plus any older per-k files
trials = plotting.load_trials(RESULTS_DIR)

# TRIAL_FILTERS, N_SE, FIXED and SNAP come from the selection cell above (weight decay fixed: negligible
# effect; trials that end up identical are averaged). Override here to explore, e.g. N_SE = 2.
tables = plotting.summarise_trials(trials, n_se=N_SE, fixed=FIXED, snap=SNAP, **TRIAL_FILTERS)

# per table: the settings all its top configs share (read down a column to compare tables)
shared  = plotting.shared_settings_table(tables)

# configs in the top of more than one table; match_on=(..., "lr") also matches lr (rounded)
common  = plotting.common_configs(tables, match_on=("hidden_dims", "dropout", "patience", "batch_size"))

# full settings of every top config
# lr rounded to 1 significant figure; weight decay fixed at the AdamW default for the runs
top_values = plotting.top_config_values(tables)   # uses the same FIXED / SNAP

in-degree 2, N = 600: best 0.1249 ± 0.0012 -> 1 of 3 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,01_256x128_lr3e-4,0.1249,0.0012,7.497,2,"[256, 128]",0.0003,0.0,20,128,687400.0,58.035,23.8724,"rmhp979u, gqtytopa"

in-degree 2, N = 1400: best 0.0443 ± 0.0006 -> 1 of 3 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,05_256x128_lr3e-4,0.0443,0.0006,7.4378,2,"[256, 128]",0.0003,0.0,20,128,687400.0,44.925,34.0855,"rmhp979u, gqtytopa"

in-degree 6, N = 600: best 0.7806 ± 0.0056 -> 6 of 55 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,40_256x128_lr3e-4,0.7806,0.0056,8.0983,1,"[256, 128]",0.00030,0.1,20,256,719144.0,135.7500,47.9705,ey794fwc
1,k6_256_128_25,0.7836,0.0057,8.0656,5,"[256, 128]",0.00030,0.1,20,128,719144.0,99.6700,41.9693,ey794fwc
2,k6_256_128_37,0.7887,0.0058,8.0391,2,"[256, 128]",0.00030,0.3,20,32,719144.0,NaN,66.2205,NaN
3,35_256x128_lr2e-4,0.7904,0.0056,8.0543,5,"[256, 128]",0.00030,0.1,20,64,719144.0,75.7175,52.8102,ey794fwc
4,k6_256_128_39,0.7912,0.0059,8.0563,7,"[256, 128]",0.00030,0.0,20,128,719144.0,106.2400,36.0489,ey794fwc
5,28_256x128_lr8e-5,0.7917,0.0053,8.1431,1,"[256, 128]",0.00006,0.1,20,64,719144.0,189.2400,115.3974,ey794fwc

in-degree 6, N = 1400: best 0.3682 ± 0.0035 -> 2 of 55 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,k6_128_64_9,0.3682,0.0035,7.8782,2,"[128, 64]",0.0003,0.1,50,128,195752.0,188.38,78.6054,ey794fwc
1,k6_128_64_5,0.3716,0.0037,7.8677,1,"[128, 64]",0.0003,0.1,100,128,195752.0,NaN,111.8904,NaN

in-degree 10, N = 600: best 2.2463 ± 0.0085 -> 4 of 28 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,09_256x128_lr3e-4,2.2463,0.0085,10.0216,7,"[256, 128]",0.0003,0.0,20,32,742696.0,33.5029,41.5610,p8lmbfxj
1,25_256x128_lr3e-4,2.2527,0.0089,10.0205,3,"[256, 128]",0.0003,0.0,100,32,742696.0,45.2867,116.2782,p8lmbfxj
2,10_256x128_lr3e-4,2.2562,0.0086,10.0347,4,"[256, 128]",0.0003,0.0,20,64,742696.0,45.3875,31.2482,p8lmbfxj
3,07_256x128_lr3e-4,2.2565,0.0085,10.0638,8,"[256, 128]",0.0003,0.0,20,128,742696.0,62.1512,25.2432,p8lmbfxj

in-degree 10, N = 1400: best 1.4160 ± 0.0076 -> 3 of 28 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,49_256x128_lr6e-4,1.4160,0.0076,9.3583,3,"[256, 128]",0.0006,0.3,20,64,742696.0,60.7633,74.7426,p8lmbfxj
1,45_256x128_lr7e-4,1.4213,0.0078,9.3505,1,"[256, 128]",0.0006,0.3,20,32,742696.0,50.6300,99.0345,p8lmbfxj
2,40_256x128_lr3e-4,1.4231,0.0081,9.3497,3,"[256, 128]",0.0003,0.3,50,32,742696.0,71.7133,168.2958,p8lmbfxj

settings shared by all top configs (within 2 kl_se) of each table (– = they differ; n_top = 1 means a single config)

,in_degree,sample_size,n_top,hidden_dims,lr,dropout,patience,batch_size
0,2,600,1,"[256, 128]",≈3e-4,0.0,20,128
1,2,1400,1,"[256, 128]",≈3e-4,0.0,20,128
2,6,600,6,"[256, 128]",–,–,20,–
3,6,1400,2,"[128, 64]",≈3e-4,0.1,–,128
4,10,600,4,"[256, 128]",≈3e-4,0.0,–,–
5,10,1400,3,"[256, 128]",–,0.3,–,–

configs (matched on hidden_dims, dropout, patience, batch_size) in the top (within 2 kl_se) of >= 2 of 6 tables: 2

,hidden_dims,dropout,patience,batch_size,n_tables,top_in,n_trials
0,"[256, 128]",0.0,20,128,4,"k2 N600, k2 N1400, k6 N600, k10 N600",4
1,"[256, 128]",0.3,20,32,2,"k6 N600, k10 N1400",2

top configs (within 2 kl_se), lr snapped to 3-6 grid; dropout snapped to 1-3 grid; weight_decay fixed at 0.01 for runs, identical configs merged:

,run_name,in_tables,n_tables,n_trials,hidden_dims,activation,lr,dropout,patience,batch_size
0,01_256x128_lr3e-4,"k2 N600, k2 N1400, k6 N600, k10 N600",4,19,"[256, 128]",ReLU,0.00030,0.0,20,128
1,09_256x128_lr3e-4,k10 N600,1,7,"[256, 128]",ReLU,0.00030,0.0,20,32
2,35_256x128_lr2e-4,k6 N600,1,5,"[256, 128]",ReLU,0.00030,0.1,20,64
3,k6_256_128_25,k6 N600,1,5,"[256, 128]",ReLU,0.00030,0.1,20,128
4,10_256x128_lr3e-4,k10 N600,1,4,"[256, 128]",ReLU,0.00030,0.0,20,64
5,25_256x128_lr3e-4,k10 N600,1,3,"[256, 128]",ReLU,0.00030,0.0,100,32
6,40_256x128_lr3e-4,k10 N1400,1,3,"[256, 128]",ReLU,0.00030,0.3,50,32
7,49_256x128_lr6e-4,k10 N1400,1,3,"[256, 128]",ReLU,0.00060,0.3,20,64
8,k6_128_64_9,k6 N1400,1,2,"[128, 64]",ReLU,0.00030,0.1,50,128
9,k6_256_128_37,k6 N600,1,2,"[256, 128]",ReLU,0.00030,0.3,20,32
10,28_256x128_lr8e-5,k6 N600,1,1,"[256, 128]",ReLU,0.00006,0.1,20,64
11,40_256x128_lr3e-4,k6 N600,1,1,"[256, 128]",ReLU,0.00030,0.1,20,256
12,45_256x128_lr7e-4,k10 N1400,1,1,"[256, 128]",ReLU,0.00060,0.3,20,32
13,k6_128_64_5,k6 N1400,1,1,"[128, 64]",ReLU,0.00030,0.1,100,128

## Candidates
### Run chosen configs on all (in-degree, sample size)
Runs specific configs on the tuning DAGs (101–105) for the in-degrees in `CAND_SWEEPS` (k = 6, 10)
and every sample size in `SWEEP_SAMPLES`, so they are compared like for like (same DAGs, data and seeds). Evaluation DAGs stay untouched. `CANDIDATES` picks rows of the
top-config table above (`top_values.loc[[...]]`, using its row numbers) or is a list of config dicts.
They are fitted exactly like sweep
trials and **added to the tuning data** (`TRIALS_CSV`, `source = "candidates"`), so the sweep tables
above include them; in W&B, each config's k=6 run is added to the k=6 sweep and its k=10 run to the k=10
sweep, tagged `candidate`. Configs already
run are skipped on re-running. The comparison table below shows just these configs. Put the chosen config(s) into `CHOSEN_NN` below.

In [ ]:
# in-degree -> existing W&B sweep: each config runs on these in-degrees, and its k=6 results go
# into the k=6 sweep, k=10 into the k=10 sweep (tagged "candidate")
CAND_SWEEPS = {6: "ey794fwc", 10: "p8lmbfxj"}

# Configs to run: rows of the top-config table above, picked by the row numbers it shows
# (or a list of config dicts written by hand). Names must be unique.
CANDIDATES = top_values.loc[[0, 1, 2, 3, 4, 13]]

# fitted exactly like sweep trials; rows are added to the tuning data (TRIALS_CSV, source="candidates",
# sweep_id of their in-degree's sweep). (config, in-degree) pairs already there are skipped on re-running.
cand = run_configs(
    CANDIDATES, k_values=list(CAND_SWEEPS), sweep_ids=CAND_SWEEPS, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    trial_csv=TRIALS_CSV, dag_offset=TUNE_DAG_OFFSET,
    wandb_project="neural-cpds-hparams",      # same project as the sweeps; None to skip W&B
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

configs:   0%|          | 0/6 [00:00<?, ?it/s]

01_256x128_lr3e-4 k=[6]: already in hparam_trials.csv, skipped
01_256x128_lr3e-4 k=[10]: already in hparam_trials.csv, skipped
09_256x128_lr3e-4 k=[6]: already in hparam_trials.csv, skipped
09_256x128_lr3e-4 k=[10]: already in hparam_trials.csv, skipped
35_256x128_lr2e-4 k=[6]: already in hparam_trials.csv, skipped
35_256x128_lr2e-4 k=[10]: already in hparam_trials.csv, skipped
k6_256_128_25 k=[6]: already in hparam_trials.csv, skipped
k6_256_128_25 k=[10]: already in hparam_trials.csv, skipped
10_256x128_lr3e-4 k=[6]: already in hparam_trials.csv, skipped
10_256x128_lr3e-4 k=[10]: already in hparam_trials.csv, skipped

KeyboardInterrupt:

### Candidate comparison
The configs run on every (in-degree, sample size) by the candidate cell above: mean KL over the
tuning DAGs. **Bold** = within `N_SE` standard errors of the best result *overall* for that
in-degree and sample size (all tuning trials, as in the sweep-results tables), not just the best candidate.

In [ ]:
# bold = within N_SE SE of the best result overall (from the sweep-results tables above;
# without `tables`, the best of all tuning trials is used)
# index = row number in top_values (same settings), for choosing the final config below
cand_table = plotting.candidate_table(plotting.load_trials(RESULTS_DIR), n_se=4,
                                      tables=globals().get("tables"),
                                      top_values=globals().get("top_values"))
if cand_table.empty:
    print("no candidate runs yet: run the candidate cell above")

chosen configs on every (in-degree, sample size): mean KL over the tuning DAGs; bold = within 4 SE of the best result overall (all tuning trials) for that in-degree and sample size; index = row in top_values

## Chosen configs
Pick the final NN config(s) for the main experiments by their `top_idx` in the candidate table above
(= row in `top_values`). The cell saves their settings to `chosen_nn.json` in the results folder;
`3_main_experiments.ipynb` reads that file and adds the `mle` and `nn_linear` baselines. The saved
choice stays fixed even if the indices change later (new trials, `N_SE` / `SNAP`), so re-run this
cell only when you want to change the final model.

In [ ]:
# top_idx of the final config(s), from the candidate table above (= row in top_values)
CHOSEN_IDX = [0,8]

save_chosen_configs(top_values.loc[CHOSEN_IDX], CHOSEN_JSON)

saved 2 config(s) to results5-parallel\chosen_nn.json: ['01_256x128_lr3e-4', 'k6_128_64_9']

[{'name': '01_256x128_lr3e-4',
  'lr': 0.0003,
  'weight_decay': 0.01,
  'dropout': 0.0,
  'patience': 20,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [256, 128],
  'activation': 'ReLU'},
 {'name': 'k6_128_64_9',
  'lr': 0.0003,
  'weight_decay': 0.01,
  'dropout': 0.1,
  'patience': 50,
  'batch_size': 128,
  'optimizer': 'adamw',
  'n_epochs': 1000,
  'hidden_dims': [128, 64],
  'activation': 'ReLU'}]