# 2. Hyperparameter tuning
Sweeps on the tuning DAGs (101–105), their results, and the candidate check that picks the config
for the main experiments in `3_main_experiments.ipynb`. Shared settings come from `1_mle.ipynb` (its `config` cell); this
notebook's own tuning and selection settings are tagged `config` too, so `3_main_experiments.ipynb` can load them.

In [1]:
%load_ext autoreload
%autoreload 2

import os
import logging

import numpy as np
import pandas as pd
import torch.nn as nn

from ndbn.experiments import run_sweep, run_configs
import ndbn.plotting as plotting
from ndbn.notebook_config import load_notebook_config

logging.getLogger("pgmpy").setLevel(logging.ERROR)

# shared settings (RESULTS_DIR, CARD, SAMPLE_SIZES, speed settings, ...) from 1_mle.ipynb
globals().update(load_notebook_config("1_mle.ipynb"))
print("results folder:", RESULTS_DIR)

results folder: results5-parallel

In [2]:
from IPython.display import HTML, display
display(HTML("""<style>
.cell-output-ipywidget-background { background-color: transparent !important; }
:root {
  --jp-widgets-color: var(--vscode-editor-foreground);
  --jp-widgets-font-size: var(--vscode-editor-font-size);
}
</style>"""))

## Sweeps
Fixed graph size, varying only the estimator. Writes its own `sweep_tune.csv`, so it
cannot contaminate the main grid's `results.csv`. All tuning runs on separate DAGs
(101–105, `TUNE_DAG_OFFSET`); the main experiment's DAGs 1–5 are kept for final evaluation.

In [3]:
%pip install wandb   
# Offline alternative (sync later with `wandb sync`):  os.environ["WANDB_MODE"] = "offline"

Requirement already satisfied: wandb in .\.venv\Lib\site-packages (0.30.0)
Requirement already satisfied: click>=8.2.0 in .\.venv\Lib\site-packages (from wandb) (8.5.0)
Requirement already satisfied: opentelemetry-api>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: opentelemetry-sdk>=1.43.0 in .\.venv\Lib\site-packages (from wandb) (1.45.0)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from wandb) (26.3)
Requirement already satisfied: platformdirs in .\.venv\Lib\site-packages (from wandb) (4.11.8)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>=5 in .\.venv\Lib\site-packages (from wandb) (7.36.2)
Requirement already satisfied: pydantic<3,>=2.6 in .\.venv\Lib\site-packages (from wandb) (2.13.5)
Requirement already satisfied: pyyaml in .\.venv\Lib\site-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in .\.venv\Lib\site-packages (from wandb) (2.34.2)
Requirement already satisfied: typing-extensions<5,>=4.8 in .\.venv\Lib\site-packages (from wandb) (4.16.0)
Requirement already satisfied: xxhash>=3.0.0 in .\.venv\Lib\site-packages (from wandb) (4.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in .\.venv\Lib\site-packages (from pydantic<3,>=2.6->wandb) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in .\.venv\Lib\site-packages (from requests<3,>=2.0.0->wandb) (2026.7.22)
Requirement already satisfied: googleapis-common-protos~=1.52 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.75.5)
Requirement already satisfied: opentelemetry-exporter-http-transport==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-http-transport[urllib3]==0.66b0->opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-common==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (0.66b0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-proto==1.45.0 in .\.venv\Lib\site-packages (from opentelemetry-exporter-otlp-proto-http>=1.43.0->wandb) (1.45.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in .\.venv\Lib\site-packages (from opentelemetry-sdk>=1.43.0->wandb) (0.66b0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import wandb
wandb.login()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Currently logged in as: kay-asp (kay-asp-wits-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [5]:
import os
import torch.nn as nn

# All tuning (architecture sweep, no-ES diagnostic, hyperparameter sweep) runs on
# separate DAGs 101..100+SWEEP_DAGS from the same generator. The main experiment's
# DAGs (1..SIM) are kept for final evaluation only.
TUNE_DAG_OFFSET = 100
assert TUNE_DAG_OFFSET >= SIM, "tuning DAGs overlap the evaluation DAGs"

WANDB_PROJECT = "neural-cpds-tune"

SWEEP_CSV     = os.path.join(RESULTS_DIR, "sweep_tune.csv")
HIST_DIR      = os.path.join(RESULTS_DIR, "histories_tune")

SWEEP_N       = 20
SWEEP_ALPHA   = 0.5
SWEEP_DAGS    = 5
SWEEP_K       = [2, 6, 10]          # widen to [2, 4, 6, 8, 10] if time allows
SWEEP_SAMPLES = [600, 1400]

ARMS = [
    {"name": "nn_linear",     "hidden_dims": (),        "activation": None},
    {"name": "nn_32",         "hidden_dims": (32,),     "activation": nn.ReLU},
    {"name": "nn_64_32",      "hidden_dims": (64, 32),  "activation": nn.ReLU},
    {"name": "nn_128_64",     "hidden_dims": (128, 64), "activation": nn.ReLU},
    {"name": "nn_32_nowd",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "weight_decay": 0.0},
    {"name": "nn_32_lr3e3",   "hidden_dims": (32,), "activation": nn.ReLU,
                              "lr": 3e-3},
    {"name": "nn_32_long",    "hidden_dims": (32,), "activation": nn.ReLU,
                              "n_epochs": 1000, "patience": 50},
]

In [6]:
sweep_df = run_sweep(
    arms=ARMS, k_values=SWEEP_K, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD,
    val_frac=VAL_FRAC, n_epochs=N_EPOCHS,
    wandb_project=WANDB_PROJECT, sweep_csv=SWEEP_CSV, hist_dir=HIST_DIR,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

sweep runs:   0%|          | 0/210 [00:00<?, ?it/s]

KeyboardInterrupt:

### No-early-stopping diagnostic
Patience > number of epochs, so nothing stops training. Shows how fast and how far each
architecture overfits at k = 10, N = 600 — compare `train_loss`, `val_loss` and `gap`
per epoch in W&B. Own project, CSV and history folder, so it can't mix with the main sweep.

In [ ]:
NO_ES_EPOCHS = 500
NO_ES_ARMS = [{**arm, "n_epochs": NO_ES_EPOCHS, "patience": 1000}
              for arm in ARMS if arm["name"] in ("nn_32", "nn_64_32", "nn_128_64")]

no_es_df = run_sweep(
    arms=NO_ES_ARMS, k_values=[10], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=[600], card=CARD,
    val_frac=VAL_FRAC, n_epochs=NO_ES_EPOCHS,
    wandb_project="neural-cpds-no-early-stopping-tune",
    sweep_csv=os.path.join(RESULTS_DIR, "sweep_no_es_tune.csv"),
    hist_dir=os.path.join(RESULTS_DIR, "histories_no_es_tune"),
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES),   # main experiment's sample budget
    n_test=N_TEST,                                         # true KL on cached test.csv
    dag_offset=TUNE_DAG_OFFSET,                            # tuning DAGs, not evaluation
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

### Hyperparameter sweep (W&B, Bayesian)
Tuning runs on **separate DAGs** (`dag_idx` > `TUNE_DAG_OFFSET`) drawn from the same generator,
never on the main experiment's DAGs. The chosen setting is then frozen and evaluated on the
main experiment's DAGs, so their test sets never influence any choice.

Each trial is one config scored on every tuning DAG × sample size for the given k. Because
the tuning DAGs are disjoint from evaluation, selecting on `mean_kl` (true KL on the tuning
DAGs' `test.csv`) is legitimate; `mean_val_loss` (validation-only) is the alternative. Both
are logged. AdamW, so `weight_decay` is decoupled and actually regularises. Start with
k = 10, then check how the frozen setting transfers to k = 2, 6.

In [7]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_K            = 10
HP_TRIALS       = 50
HP_METRIC       = "mean_kl"      # or "mean_val_loss" (validation-only selection)

HP_CONFIG = {
    "name": f"{HP_METRIC}_c{CARD}_k{HP_K}",                 # sweep name shown in W&B (else a random id)
    "description": f"card {CARD}, in-degree {HP_K}, tuning DAGs {TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, "
                   f"N = {SWEEP_SAMPLES}, minimising {HP_METRIC}",
    "method": "bayes",
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": {
        "hidden_dims":  {"values": ["32", "64_32", "128_64", "256_128"]},
        "lr":           {"distribution": "log_uniform_values", "min": 3e-4, "max": 1e-2},
        "weight_decay": {"distribution": "log_uniform_values", "min": 1e-5, "max": 1e-1},
        "dropout":      {"values": [0.0, 0.1, 0.2, 0.3, 0.5]},
        "patience":     {"values": [20, 50, 100]},
        "batch_size":   {"values": [32, 64, 128]},
        "optimizer":    {"value": "adamw"},
        # "activation": {"values": ["relu", "tanh", "gelu"]},   # optional; default relu
        "n_epochs":     {"value": 1000},
    },
}

In [ ]:
HP_K = 10
hp_sweep_id = 'p8lmbfxj' # wandb.sweep(HP_CONFIG, project=HP_PROJECT)   # or reuse an existing id to resume

run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: p8lmbfxj
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/p8lmbfxj

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ckm5nlz5 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0006490571148348818
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.02142725152145705

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6bd3krb1 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0010794742484677405
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 0.018281353070021347

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tyrhyj43 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.2
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.007086766095599365
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.00012300066375472136

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ch1c6rrt with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.5
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0004398905142903079
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 1.3959458299697156e-05

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3l0u1nsr with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0018047920308158728
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.00016196791415874794

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: p48276bh with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031979724450392847
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 0.015520011880241722

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: k6ig9ay5 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003066241935747525
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0007312861851286882

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: iwdqb26p with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003575854610841874
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.008111342046621665

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3fiyohnd with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003021385418257858
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0008554858452484091

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ri4iwcj7 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003426881685375807
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.04226470479035765

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4pswn95r with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00032955667436562953
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0002621118264019291

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4na788k7 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003530429876074674
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.011297890580020509

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3u2n1lh9 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003051361448378743
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.08515895577313541

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: uayk6beu with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003465615497712979
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.017788328006113997

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: efoa83xg with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031711017328810365
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.06456213963908328

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: d8ppbjc8 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004513797624872242
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0031219981856768155

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4wh94aok with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00034996728563335585
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.0018603735837672236

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5hh0iwsv with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00033879416071749694
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 2.4546158750122363e-05

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: m9cl6voy with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00030846986959326693
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.0058220865120883645

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0wyfsj65 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003030050204669698
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.00151963258046676

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: avt1thsf with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031867681935603115
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 0.0001616159370378949

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 9fi97hjq with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003088922730214041
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0002869782629456647

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 1bpxz5xr with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003250506515156642
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 8.628727029483195e-05

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: z7p98fox with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00030713306044757925
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 0.0010671190421588576

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 9mvxeayn with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031195774432661084
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 100
wandb: 	weight_decay: 0.000158094921224059

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: o0zxqxw3 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00032962244673078215
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.03294467968512384

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7rdltasb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00032402700028016056
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01935582978236233

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: n5ja71an with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003347280794775159
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 3.07489804703603e-05

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: q1xs3fec with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003081558024044561
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.001620440184286052

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7e1m9ep3 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031026274761587416
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0035232233781100778

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: e3ymm07w with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004119645102744782
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.008592667660010917

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: rgoybvod with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.2
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003159732066636527
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0014070481771817891

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: juea0xji with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003640829890551172
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0008483741621653798

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6r8am1aa with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004212608581937983
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.030463919924605492

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ti4083im with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003070727949314167
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.011483962420286596

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: iapkywx1 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003935572603259555
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0260031451847962

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: qftl45rx with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004208989881954892
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.024015632507201703

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: k5mp7zkb with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.00034353932917658456
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01600267818974684

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: mjj5vx5v with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0003497947038223437
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0055109332000139

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 5dnk1pnw with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003094712768007069
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.005088573055464021

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: x8x69yba with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.2
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003351699484873379
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.0004233197647880687

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: reqa7eta with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004408091543846099
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.003440412277063461

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: tvbtvieb with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00033738607381448476
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.01997858612572001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4q3xj892 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0010429252195678412
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.05671798203802184

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ezi1zrq9 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.5
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0006891757812417602
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.011363323298084272

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: asz1yrjm with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0003522395894526955
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 5.23835485702941e-05

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ozoxagrf with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.000393658981685491
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 50
wandb: 	weight_decay: 0.08718750679722573

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: vg0n9vh1 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.3
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004703383982102582
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.051690487554598194

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: b46fhhhc with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.5
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0006352461576126954
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.05778575724018419

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: c8cpbwfb with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.5
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007442032736754118
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.02929431025378846

In [ ]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_K            = 6
HP_TRIALS       = 50
HP_METRIC       = "mean_kl"      # or "mean_val_loss" (validation-only selection)

HP_CONFIG = {
    "name": f"{HP_METRIC}_c{CARD}_k{HP_K}",                 # sweep name shown in W&B (else a random id)
    "description": f"card {CARD}, in-degree {HP_K}, tuning DAGs {TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, "
                   f"N = {SWEEP_SAMPLES}, minimising {HP_METRIC}",
    "method": "bayes",
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": {
        "hidden_dims":  {"values": ["32", "64_32", "128_64", "256_128"]},
        "lr":           {"distribution": "log_uniform_values", "min": 3e-5, "max": 1e-3},
        "weight_decay": {"value": 1e-4},
        "dropout":      {"values": [0.0, 0.1]},
        "patience":     {"values": [5, 10, 20]},
        "batch_size":   {"values": [64, 128, 256]},
        "optimizer":    {"value": "adamw"},
        # "activation": {"values": ["relu", "tanh", "gelu"]},   # optional; default relu
        "n_epochs":     {"value": 1000},
    },
}

In [ ]:
HP_K = 6
hp_sweep_id = 'ey794fwc'  # or reuse an existing id to resume

run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: ey794fwc
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/ey794fwc

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: lkee28ae with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 7.667716223070097e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: lb30h9qy with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0007043242037296014
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: jvrcwctk with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 5.5158651418470695e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: q34are6j with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 6.10471022427045e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: lylym9es with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0007588524228910477
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: n4r6rgmt with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0005730226773342534
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0q1o71mf with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.000984333100399876
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kz1zlu6p with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.000777590817804881
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 8882d6ma with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0009971474604872636
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hqu1ypvo with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0008083461478331675
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6wydo9tc with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0009916914421346371
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4m4ov212 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0009069641309329596
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: n8c9lm0d with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007261982485486449
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7wye27yg with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007689625436870138
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 43dm1alw with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007177359236191609
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 0dyra6vo with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0009543546730461654
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hj0jlt9r with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0005737869580829157
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: h7277w2k with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00031936563050327064
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: j02zwgk9 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0005786066733977498
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: oapmr52a with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007806995912989926
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 6b93b32d with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0009916010978475072
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kehha82r with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0005052046691357864
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: p8yj4w73 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007184764629378717
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: nd1x3bcl with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003391617428469736
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: cdaw28my with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0004947282347613858
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ynjzo24w with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0005856199364538008
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: o4ldvfu7 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007031806436340798
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kq6g2wnc with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 8.004871128610993e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: nju2ygn8 with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007853443061113378
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: wdfnpl0w with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0009203711402923814
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: j1e1jx5l with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0007657883496159457
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: am41m7eb with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00023958896500170989
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 55ghpuow with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0006361857553645792
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2eovg9bw with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0009825956931549275
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: ycrt6hfo with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00020556454378026229
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: jodf4znk with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0009692935700082428
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: xgve6xwo with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0008564504132838338
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: u16v30oz with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00070914896838989
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: w2ky0hdq with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0006358314135428195
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 3qaxlivy with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.0003107758775646299
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: exx5gu9h with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 64_32
wandb: 	lr: 8.240213826279417e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: kn7jzynb with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 0.0001250532556883339
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: fzo0tsqu with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 0.00019262331498731355
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: mdbji7ed with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0006067460368248471
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: iiixjlqp with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0005611335326010833
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: czrk4lsh with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.0008271445034309195
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 7nwbrx57 with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0
wandb: 	hidden_dims: 64_32
wandb: 	lr: 0.0001255441109108312
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 5
wandb: 	weight_decay: 0.0001

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: hce7xwds with config:
wandb: 	batch_size: 256
wandb: 	dropout: 0
wandb: 	hidden_dims: 256_128
wandb: 	lr: 0.00044524047109538857
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 2bx6snxj with config:
wandb: 	batch_size: 64
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 32
wandb: 	lr: 9.011172768233074e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.0001

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: b3t1w1t7 with config:
wandb: 	batch_size: 128
wandb: 	dropout: 0
wandb: 	hidden_dims: 32
wandb: 	lr: 7.364868362695847e-05
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 10
wandb: 	weight_decay: 0.0001

In [ ]:
from functools import partial
from ndbn.experiments import sweep_trial

HP_PROJECT      = "neural-cpds-hparams"
HP_K            = 10
HP_TRIALS       = 30
HP_METRIC       = "mean_kl"      # or "mean_val_loss" (validation-only selection)

HP_CONFIG = {
    "name": f"{HP_METRIC}_c{CARD}_k{HP_K}",                 # sweep name shown in W&B (else a random id)
    "description": f"card {CARD}, in-degree {HP_K}, tuning DAGs {TUNE_DAG_OFFSET + 1}-{TUNE_DAG_OFFSET + SWEEP_DAGS}, "
                   f"N = {SWEEP_SAMPLES}, minimising {HP_METRIC}",
    "method": "bayes",
    "metric": {"name": HP_METRIC, "goal": "minimize"},
    "parameters": {
        "hidden_dims":  {"values": ["32", "64_32", "128_64", "256_128"]},
        "lr":           {"distribution": "log_uniform_values", "min": 1e-5, "max": 1e-3},
        "weight_decay": {"distribution": "log_uniform_values", "min": 1e-5, "max": 1e-1},
        "dropout":      {"values": [0.0, 0.1, 0.3, 0.5]},
        "patience":     {"values": [20, 50, 100]},
        "batch_size":   {"values": [32, 64, 128]},
        "optimizer":    {"value": "adamw"},
        # "activation": {"values": ["relu", "tanh", "gelu"]},   # optional; default relu
        "n_epochs":     {"value": 1000},
    },
}

In [ ]:
HP_K = 2
hp_sweep_id = "gqtytopa" #wandb.sweep(HP_CONFIG, project=HP_PROJECT)

run_trial = partial(
    sweep_trial, k_values=[HP_K], n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    # one file for every sweep: each row records all its settings + sweep_id
    trial_csv=TRIALS_CSV,
    dag_offset=TUNE_DAG_OFFSET,
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

from tqdm.auto import tqdm
bar = tqdm(total=HP_TRIALS, desc="sweep trials")

def trial():
    try:
        run_trial()
    finally:
        bar.update()          # counts even if a trial fails

wandb.agent(hp_sweep_id, project=HP_PROJECT, count=HP_TRIALS, function=trial)
bar.close()

Create sweep with ID: gqtytopa
Sweep URL: https://wandb.ai/kay-asp-wits-university/neural-cpds-hparams/sweeps/gqtytopa

sweep trials:   0%|          | 0/50 [00:00<?, ?it/s]

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from C:\Users\Kaylin\_netrc.
wandb: Agent Starting Run: 4wbugbg0 with config:
wandb: 	batch_size: 32
wandb: 	dropout: 0.1
wandb: 	hidden_dims: 128_64
wandb: 	lr: 0.007141661176827854
wandb: 	n_epochs: 1000
wandb: 	optimizer: adamw
wandb: 	patience: 20
wandb: 	weight_decay: 0.00108400144426591

## Hyperparameter sweep results
From `hparam_trials.csv` (every sweep; each row records all its settings and its `sweep_id`),
filtered with `TRIAL_FILTERS` (any recorded column). Weight decay was found to have a negligible effect
on KL, so it is fixed at the AdamW default of 0.01 (`FIXED`, set in the selection cell above); trials whose
settings are then identical (after rounding, or `SNAP`) are averaged automatically. One table per (in-degree, sample size): the configs
whose mean KL over the tuning DAGs is within one `kl_se` of that pair's best. Then one table of the
settings each pair's top configs share, and the configs that are in the top of more than one table, matched on `match_on` (add e.g. `"lr"`, rounded to 1
significant figure).

In [ ]:
# Sweep-result selection (used by the sweep results and candidate cells below)
TRIAL_FILTERS = dict(card=CARD)   # any recorded column, e.g. alpha=SWEEP_ALPHA, sweep_id=...
N_SE          = 2                 # a config is "top" if its mean KL is within N_SE kl_se of the best

# Weight decay was found to have a negligible effect on KL (a 10x change in weight decay moves
# regret by <= ~0.2 percentage points with the other settings fixed), so it is fixed at the AdamW
# default 0.01: trials that then have identical settings are averaged automatically, and every
# chosen config runs with weight decay 0.01.
FIXED         = {"weight_decay": 0.01}
SNAP          = (("lr", (3,6)), ("dropout", (1,3)) )                # e.g. (("lr", (1, 3)),) to snap lr to 1e-4, 3e-4, 1e-3, ...

In [ ]:
# hparam_trials.csv (all sweeps) plus any older per-k files
trials = plotting.load_trials(RESULTS_DIR)

# TRIAL_FILTERS, N_SE, FIXED and SNAP come from the selection cell above (weight decay fixed: negligible
# effect; trials that end up identical are averaged). Override here to explore, e.g. N_SE = 2.
tables = plotting.summarise_trials(trials, n_se=N_SE, fixed=FIXED, snap=SNAP, **TRIAL_FILTERS)

# per table: the settings all its top configs share (read down a column to compare tables)
shared  = plotting.shared_settings_table(tables)

# configs in the top of more than one table; match_on=(..., "lr") also matches lr (rounded)
common  = plotting.common_configs(tables, match_on=("hidden_dims", "dropout", "patience", "batch_size"))

# full settings of every top config
# lr rounded to 1 significant figure; weight decay fixed at the AdamW default for the runs
top_values = plotting.top_config_values(tables)   # uses the same FIXED / SNAP

in-degree 6, N = 600: best 0.7806 ± 0.0056 -> 6 of 55 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,40_256x128_lr3e-4,0.7806,0.0056,8.0983,1,"[256, 128]",0.00030,0.1,20,256,719144.0,135.7500,47.9705,ey794fwc
1,k6_256_128_25,0.7841,0.0057,8.0653,4,"[256, 128]",0.00030,0.1,20,128,719144.0,NaN,40.7341,NaN
2,k6_256_128_37,0.7887,0.0058,8.0391,2,"[256, 128]",0.00030,0.3,20,32,719144.0,NaN,66.2205,NaN
3,35_256x128_lr2e-4,0.7899,0.0056,8.0562,4,"[256, 128]",0.00030,0.1,20,64,719144.0,78.3867,52.9790,ey794fwc
4,k6_256_128_39,0.7914,0.0059,8.0556,5,"[256, 128]",0.00030,0.0,20,128,719144.0,NaN,32.2723,NaN
5,28_256x128_lr8e-5,0.7917,0.0053,8.1431,1,"[256, 128]",0.00006,0.1,20,64,719144.0,189.2400,115.3974,ey794fwc

in-degree 6, N = 1400: best 0.3684 ± 0.0035 -> 2 of 55 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,k6_128_64_9,0.3684,0.0035,7.8785,1,"[128, 64]",0.0003,0.1,50,128,195752.0,NaN,74.9822,NaN
1,k6_128_64_5,0.3716,0.0037,7.8677,1,"[128, 64]",0.0003,0.1,100,128,195752.0,NaN,111.8904,NaN

in-degree 10, N = 600: best 2.2461 ± 0.0085 -> 4 of 25 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,09_256x128_lr3e-4,2.2461,0.0085,10.0219,6,"[256, 128]",0.0003,0.0,20,32,742696.0,33.2500,41.1908,p8lmbfxj
1,25_256x128_lr3e-4,2.2527,0.0089,10.0205,3,"[256, 128]",0.0003,0.0,100,32,742696.0,45.2867,116.2782,p8lmbfxj
2,07_256x128_lr3e-4,2.2591,0.0085,10.0625,6,"[256, 128]",0.0003,0.0,20,128,742696.0,60.1050,24.3364,p8lmbfxj
3,10_256x128_lr3e-4,2.2598,0.0086,10.0356,3,"[256, 128]",0.0003,0.0,20,64,742696.0,44.8100,30.3163,p8lmbfxj

in-degree 10, N = 1400: best 1.4160 ± 0.0076 -> 3 of 25 configs (weight_decay fixed at 0.01) (lr snapped to 3-6 grid) (dropout snapped to 1-3 grid) within 2 kl_se

,run_name,mean_kl,kl_se,mean_val_loss,n_trials,hidden_dims,lr,dropout,patience,batch_size,stored_params,best_epoch_mean,fit_time_s,sweep_id
0,49_256x128_lr6e-4,1.4160,0.0076,9.3583,3,"[256, 128]",0.0006,0.3,20,64,742696.0,60.7633,74.7426,p8lmbfxj
1,45_256x128_lr7e-4,1.4213,0.0078,9.3505,1,"[256, 128]",0.0006,0.3,20,32,742696.0,50.6300,99.0345,p8lmbfxj
2,40_256x128_lr3e-4,1.4231,0.0081,9.3497,3,"[256, 128]",0.0003,0.3,50,32,742696.0,71.7133,168.2958,p8lmbfxj

settings shared by all top configs (within 2 kl_se) of each table (– = they differ; n_top = 1 means a single config)

,in_degree,sample_size,n_top,hidden_dims,lr,dropout,patience,batch_size
0,6,600,6,"[256, 128]",–,–,20,–
1,6,1400,2,"[128, 64]",≈3e-4,0.1,–,128
2,10,600,4,"[256, 128]",≈3e-4,0.0,–,–
3,10,1400,3,"[256, 128]",–,0.3,–,–

configs (matched on hidden_dims, dropout, patience, batch_size) in the top (within 2 kl_se) of >= 2 of 4 tables: 2

,hidden_dims,dropout,patience,batch_size,n_tables,top_in,n_trials
0,"[256, 128]",0.0,20,128,2,"k6 N600, k10 N600",2
1,"[256, 128]",0.3,20,32,2,"k6 N600, k10 N1400",2

top configs (within 2 kl_se), lr snapped to 3-6 grid; dropout snapped to 1-3 grid; weight_decay fixed at 0.01 for runs, identical configs merged:

,run_name,in_tables,n_tables,n_trials,hidden_dims,activation,lr,dropout,patience,batch_size
0,07_256x128_lr3e-4,"k6 N600, k10 N600",2,11,"[256, 128]",ReLU,0.00030,0.0,20,128
1,09_256x128_lr3e-4,k10 N600,1,6,"[256, 128]",ReLU,0.00030,0.0,20,32
2,35_256x128_lr2e-4,k6 N600,1,4,"[256, 128]",ReLU,0.00030,0.1,20,64
3,k6_256_128_25,k6 N600,1,4,"[256, 128]",ReLU,0.00030,0.1,20,128
4,10_256x128_lr3e-4,k10 N600,1,3,"[256, 128]",ReLU,0.00030,0.0,20,64
5,25_256x128_lr3e-4,k10 N600,1,3,"[256, 128]",ReLU,0.00030,0.0,100,32
6,40_256x128_lr3e-4,k10 N1400,1,3,"[256, 128]",ReLU,0.00030,0.3,50,32
7,49_256x128_lr6e-4,k10 N1400,1,3,"[256, 128]",ReLU,0.00060,0.3,20,64
8,k6_256_128_37,k6 N600,1,2,"[256, 128]",ReLU,0.00030,0.3,20,32
9,28_256x128_lr8e-5,k6 N600,1,1,"[256, 128]",ReLU,0.00006,0.1,20,64
10,40_256x128_lr3e-4,k6 N600,1,1,"[256, 128]",ReLU,0.00030,0.1,20,256
11,45_256x128_lr7e-4,k10 N1400,1,1,"[256, 128]",ReLU,0.00060,0.3,20,32
12,k6_128_64_5,k6 N1400,1,1,"[128, 64]",ReLU,0.00030,0.1,100,128
13,k6_128_64_9,k6 N1400,1,1,"[128, 64]",ReLU,0.00030,0.1,50,128

## Candidates
### Run chosen configs on all (in-degree, sample size)
Runs specific configs on the tuning DAGs (101–105) for the in-degrees in `CAND_SWEEPS` (k = 6, 10)
and every sample size in `SWEEP_SAMPLES`, so they are compared like for like (same DAGs, data and seeds). Evaluation DAGs stay untouched. `CANDIDATES` picks rows of the
top-config table above (`top_values.loc[[...]]`, using its row numbers) or is a list of config dicts.
They are fitted exactly like sweep
trials and **added to the tuning data** (`TRIALS_CSV`, `source = "candidates"`), so the sweep tables
above include them; in W&B, each config's k=6 run is added to the k=6 sweep and its k=10 run to the k=10
sweep, tagged `candidate`. Configs already
run are skipped on re-running. The comparison table below shows just these configs. Put the chosen config into `ESTIMATORS` in `3_main_experiments.ipynb`.

In [ ]:
# in-degree -> existing W&B sweep: each config runs on these in-degrees, and its k=6 results go
# into the k=6 sweep, k=10 into the k=10 sweep (tagged "candidate")
CAND_SWEEPS = {6: "ey794fwc", 10: "p8lmbfxj"}

# Configs to run: rows of the top-config table above, picked by the row numbers it shows
# (or a list of config dicts written by hand). Names must be unique.
CANDIDATES = top_values.loc[[0, 1, 2, 3, 4, 13]]

# fitted exactly like sweep trials; rows are added to the tuning data (TRIALS_CSV, source="candidates",
# sweep_id of their in-degree's sweep). (config, in-degree) pairs already there are skipped on re-running.
cand = run_configs(
    CANDIDATES, k_values=list(CAND_SWEEPS), sweep_ids=CAND_SWEEPS, n_dags=SWEEP_DAGS, n_nodes=SWEEP_N,
    alpha=SWEEP_ALPHA, sample_sizes=SWEEP_SAMPLES, card=CARD, val_frac=VAL_FRAC,
    results_dir=RESULTS_DIR, n_cached=max(SAMPLE_SIZES), n_test=N_TEST,
    trial_csv=TRIALS_CSV, dag_offset=TUNE_DAG_OFFSET,
    wandb_project="neural-cpds-hparams",      # same project as the sweeps; None to skip W&B
    n_jobs=N_JOBS, device=DEVICE_OVERRIDE, torch_threads=TORCH_THREADS,
)

configs:   0%|          | 0/6 [00:00<?, ?it/s]

KeyboardInterrupt:

### Candidate comparison
The configs run on every (in-degree, sample size) by the candidate cell above:
mean KL over the tuning DAGs and regret % against the best config in each pair.

In [ ]:
cand_table = plotting.candidate_table(plotting.load_trials(RESULTS_DIR))
if cand_table.empty:
    print("no candidate runs yet: run the candidate cell above")